export const LINE_WEBHOOK_COPY = {
  th: {
    title: "LINE Webhook",
    backToList: "กลับไปรายการ",
    statusReady: "พร้อมใช้งาน",
    statusEmpty: "ยังไม่ตั้งค่า",
    publicUrl: "Public URL",
    publicUrlPlaceholder: "https://example.ngrok-free.app",
    channelSecret: "Channel Secret",
    channelSecretPlaceholder: "กรอก Channel Secret",
    callbackUrl: "Webhook URL",
    callbackEmpty: "กรอก Public URL ก่อน",
    copy: "คัดลอก",
    copied: "คัดลอกแล้ว",
    openConsole: "LINE Developers",
    save: "บันทึก",
    saving: "กำลังบันทึก…",
    saved: "บันทึกแล้ว",
    errPublicUrl: "กรอก HTTPS public URL เท่านั้น",
    errSecret: "กรอก Channel Secret",
    errSave: "บันทึกไม่สำเร็จ",
  },
  en: {
    title: "LINE Webhook",
    backToList: "Back to list",
    statusReady: "Configured",
    statusEmpty: "Not configured",
    publicUrl: "Public URL",
    publicUrlPlaceholder: "https://example.ngrok-free.app",
    channelSecret: "Channel Secret",
    channelSecretPlaceholder: "Enter channel secret",
    callbackUrl: "Webhook URL",
    callbackEmpty: "Enter a public URL first",
    copy: "Copy",
    copied: "Copied",
    openConsole: "LINE Developers",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    errPublicUrl: "Enter an HTTPS public URL",
    errSecret: "Enter the channel secret",
    errSave: "Could not save",
  },
  ja: {
    title: "LINE Webhook",
    backToList: "一覧に戻る",
    statusReady: "設定済み",
    statusEmpty: "未設定",
    publicUrl: "Public URL",
    publicUrlPlaceholder: "https://example.ngrok-free.app",
    channelSecret: "Channel Secret",
    channelSecretPlaceholder: "Channel Secret を入力",
    callbackUrl: "Webhook URL",
    callbackEmpty: "先に Public URL を入力してください",
    copy: "コピー",
    copied: "コピーしました",
    openConsole: "LINE Developers",
    save: "保存",
    saving: "保存中…",
    saved: "保存しました",
    errPublicUrl: "HTTPS の Public URL を入力してください",
    errSecret: "Channel Secret を入力してください",
    errSave: "保存に失敗しました",
  },
} as const;
