export const LINE_WEBHOOK_COPY = {
  th: {
    title: "LINE Webhook",
    backToList: "กลับไปรายการ",
    statusReady: "พร้อมใช้งาน",
    statusEmpty: "ยังไม่ตั้งค่า",
    hint: "ค่าเหล่านี้บันทึกลง Supabase (Secret / Access Token ถูกเข้ารหัส) เพื่อให้ Vercel / LINE Verify / Rich menu ใช้งานได้",
    storageSupabase: "บันทึกใน Supabase แล้ว",
    storageEnv: "กำลังใช้ค่าจาก Environment Variables",
    storageMixed: "มีทั้งค่าใน Env และ Supabase (Env มีลำดับสูงกว่าตอน webhook)",
    storageFile: "ยังใช้ไฟล์ local อยู่",
    needSupabase: "ต้องตั้งค่า SUPABASE_URL และ SUPABASE_SERVICE_ROLE_KEY ก่อนบันทึก",
    publicUrl: "Public URL",
    publicUrlPlaceholder: "https://sam-bridge.vercel.app",
    channelSecret: "Channel Secret (Messaging API)",
    channelSecretPlaceholder: "กรอก Channel Secret",
    channelSecretHint: "จาก LINE Developers → Messaging API → Basic settings",
    channelAccessToken: "Channel Access Token (Messaging API)",
    channelAccessTokenPlaceholder: "กรอก Channel Access Token",
    channelAccessTokenHint: "จาก Messaging API → Channel access token — ใช้สลับ Rich menu หลัง login",
    liffId: "LIFF ID",
    liffIdPlaceholder: "2011288734-Sr9ywO6V",
    loginChannelId: "LINE Login Channel ID",
    loginChannelIdPlaceholder: "2011288734",
    callbackUrl: "Webhook URL",
    callbackEmpty: "กรอก Public URL ก่อน",
    copy: "คัดลอก",
    copied: "คัดลอกแล้ว",
    openConsole: "LINE Developers",
    save: "บันทึกลง Supabase",
    saving: "กำลังบันทึก…",
    saved: "บันทึกลง Supabase แล้ว",
    errPublicUrl: "กรอก HTTPS public URL เท่านั้น",
    errSecret: "กรอก Channel Secret",
    errAccessToken: "กรอก Channel Access Token",
    errLiff: "กรอก LIFF ID",
    errLoginChannel: "กรอก LINE Login Channel ID",
    errSupabase: "ยังไม่ได้ตั้งค่า Supabase",
    errEncrypt: "ยังไม่ได้ตั้งค่า CONNECTIONS_ENCRYPTION_KEY (หรือ AUTH_PASSWORD)",
    errSave: "บันทึกไม่สำเร็จ",
  },
  en: {
    title: "LINE Webhook",
    backToList: "Back to list",
    statusReady: "Configured",
    statusEmpty: "Not configured",
    hint: "These values are stored in Supabase (secret and access token encrypted) for Vercel, LINE Verify, and rich menus.",
    storageSupabase: "Saved in Supabase",
    storageEnv: "Using environment variables",
    storageMixed: "Both env and Supabase are set (env wins for webhook)",
    storageFile: "Using local file storage",
    needSupabase: "Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY before saving",
    publicUrl: "Public URL",
    publicUrlPlaceholder: "https://sam-bridge.vercel.app",
    channelSecret: "Channel Secret (Messaging API)",
    channelSecretPlaceholder: "Enter channel secret",
    channelSecretHint: "From LINE Developers → Messaging API → Basic settings",
    channelAccessToken: "Channel Access Token (Messaging API)",
    channelAccessTokenPlaceholder: "Enter channel access token",
    channelAccessTokenHint: "From Messaging API → Channel access token — used to switch rich menus after login",
    liffId: "LIFF ID",
    liffIdPlaceholder: "2011288734-Sr9ywO6V",
    loginChannelId: "LINE Login Channel ID",
    loginChannelIdPlaceholder: "2011288734",
    callbackUrl: "Webhook URL",
    callbackEmpty: "Enter a public URL first",
    copy: "Copy",
    copied: "Copied",
    openConsole: "LINE Developers",
    save: "Save to Supabase",
    saving: "Saving…",
    saved: "Saved to Supabase",
    errPublicUrl: "Enter an HTTPS public URL",
    errSecret: "Enter the channel secret",
    errAccessToken: "Enter the channel access token",
    errLiff: "Enter the LIFF ID",
    errLoginChannel: "Enter the LINE Login Channel ID",
    errSupabase: "Supabase is not configured",
    errEncrypt: "Set CONNECTIONS_ENCRYPTION_KEY (or AUTH_PASSWORD)",
    errSave: "Could not save",
  },
  ja: {
    title: "LINE Webhook",
    backToList: "一覧に戻る",
    statusReady: "設定済み",
    statusEmpty: "未設定",
    hint: "これらの値は Supabase に保存されます（Secret / Access Token は暗号化）。Vercel / LINE Verify / Rich menu で利用します。",
    storageSupabase: "Supabase に保存済み",
    storageEnv: "環境変数を使用中",
    storageMixed: "Env と Supabase の両方あり（Webhook は Env 優先）",
    storageFile: "ローカルファイルを使用中",
    needSupabase: "保存前に SUPABASE_URL と SUPABASE_SERVICE_ROLE_KEY を設定してください",
    publicUrl: "Public URL",
    publicUrlPlaceholder: "https://sam-bridge.vercel.app",
    channelSecret: "Channel Secret (Messaging API)",
    channelSecretPlaceholder: "Channel Secret を入力",
    channelSecretHint: "LINE Developers → Messaging API → Basic settings",
    channelAccessToken: "Channel Access Token (Messaging API)",
    channelAccessTokenPlaceholder: "Channel Access Token を入力",
    channelAccessTokenHint: "Messaging API → Channel access token — ログイン後のリッチメニュー切替に使用",
    liffId: "LIFF ID",
    liffIdPlaceholder: "2011288734-Sr9ywO6V",
    loginChannelId: "LINE Login Channel ID",
    loginChannelIdPlaceholder: "2011288734",
    callbackUrl: "Webhook URL",
    callbackEmpty: "先に Public URL を入力してください",
    copy: "コピー",
    copied: "コピーしました",
    openConsole: "LINE Developers",
    save: "Supabase に保存",
    saving: "保存中…",
    saved: "Supabase に保存しました",
    errPublicUrl: "HTTPS の Public URL を入力してください",
    errSecret: "Channel Secret を入力してください",
    errAccessToken: "Channel Access Token を入力してください",
    errLiff: "LIFF ID を入力してください",
    errLoginChannel: "LINE Login Channel ID を入力してください",
    errSupabase: "Supabase が未設定です",
    errEncrypt: "CONNECTIONS_ENCRYPTION_KEY（または AUTH_PASSWORD）を設定してください",
    errSave: "保存に失敗しました",
  },
} as const;
