export const SOURCE_COPY = {
  th: {
    title: "Data Sources",
    subtitle: "กำหนดข้อมูลที่ SAM Bridge จะรับเข้าจากระบบธุรกิจ เครื่องจักร ไฟล์ และหน้างาน",
    create: "เพิ่ม Data Source",
    nameCol: "ชื่อ",
    connectorCol: "Connector",
    statusCol: "สถานะ",
    actionsCol: "จัดการ",
    emptyTitle: "ยังไม่มี Data Source",
    drafts: "Source Drafts",
    connectorTypes: "Connector Types",
    dataDomains: "Data Domains",
    configured: "Source ที่ตั้งค่าไว้",
    configuredHint: "ทุก Source ยังเป็น Draft และยังไม่มีการเชื่อมต่อระบบจริง",
    empty: "ยังไม่มี Source Draft กดเพิ่ม Data Source เพื่อเริ่มออกแบบการรับข้อมูล",
    catalog: "Source Catalog",
    catalogHint: "เลือกวิธีที่ระบบต้นทางสามารถส่งหรือให้ SAM Bridge อ่านข้อมูลได้",
    configure: "ตั้งค่า",
    edit: "แก้ไข",
    remove: "ลบ",
    draft: "Draft",
    site: "โรงงาน / Site",
    owner: "ผู้ดูแล",
    mode: "รูปแบบการรับ",
    domains: "ข้อมูล",
    updated: "แก้ไขล่าสุด",
    deleteTitle: "ลบ Source Draft นี้?",
    deleteBody: "การตั้งค่า Draft จะถูกลบ แต่จะไม่กระทบระบบต้นทางใด ๆ",
    cancel: "ยกเลิก",
    confirmDelete: "ลบ Draft",
    back: "Data Sources",
    newTitle: "เพิ่ม Data Source",
    editTitle: "แก้ไข Data Source",
    stepConnector: "Connector",
    stepConnection: "Connection",
    stepData: "Data",
    stepReview: "Review",
    connectorHeading: "เลือก Source Connector",
    connectorLead: "เริ่มจากวิธีที่ข้อมูลออกจากระบบต้นทาง โดยยังไม่ต้องใส่ Credential จริง",
    connectionHeading: "อธิบาย Source และ Connection",
    connectionLead: "ข้อมูลส่วนนี้ใช้สร้าง Draft และเตรียมหน้าตั้งค่าจริงในขั้นต่อไป",
    sourceName: "ชื่อ Source",
    sourceNamePlaceholder: "SAP Production Orders",
    description: "คำอธิบาย",
    descriptionPlaceholder: "ข้อมูลนี้มาจากไหนและใช้ทำอะไร",
    auth: "Authentication",
    schedule: "Polling interval",
    minutes: "นาที",
    credentialsNotice: "UX Preview เท่านั้น — Credential, Password และ Certificate จะไม่ถูกบันทึกในหน้านี้",
    dataHeading: "เลือกข้อมูลที่ต้องการรับเข้า",
    dataLead: "หนึ่ง Source สามารถส่งข้อมูลได้หลาย Domain และจะถูกแปลงเป็น SAM Event มาตรฐาน",
    selected: "รายการที่เลือก",
    eventPreview: "SAM Event Preview",
    reviewHeading: "ตรวจสอบ Source Draft",
    reviewLead: "หลังบันทึก Source จะยังไม่เชื่อมต่อหรือดึงข้อมูลจริง",
    save: "บันทึก Source Draft",
    saving: "กำลังบันทึก…",
    continue: "ดำเนินการต่อ",
    previous: "ย้อนกลับ",
    required: "กรอกชื่อ Source เลือก Connector และเลือกข้อมูลอย่างน้อยหนึ่งประเภท",
    saveError: "บันทึก Source Draft ไม่สำเร็จ",
    notFound: "ไม่พบ Source Draft",
    previewOnly: "Design only · No inbound data",
  },
  en: {
    title: "Data Sources", subtitle: "Define what SAM Bridge receives from business systems, machines, files and shop-floor teams.", create: "Add data source", nameCol: "Name", connectorCol: "Connector", statusCol: "Status", actionsCol: "Actions", emptyTitle: "No data sources", drafts: "Source drafts", connectorTypes: "Connector types", dataDomains: "Data domains", configured: "Configured sources", configuredHint: "Every source remains a draft and no external connection is active.", empty: "No source drafts yet. Add a data source to begin designing inbound data.", catalog: "Source catalog", catalogHint: "Choose how the source system can push data or let SAM Bridge read it.", configure: "Configure", edit: "Edit", remove: "Delete", draft: "Draft", site: "Plant / site", owner: "Owner", mode: "Ingestion", domains: "Data", updated: "Updated", deleteTitle: "Delete this source draft?", deleteBody: "The draft configuration will be removed without affecting any source system.", cancel: "Cancel", confirmDelete: "Delete draft", back: "Data Sources", newTitle: "Add data source", editTitle: "Edit data source", stepConnector: "Connector", stepConnection: "Connection", stepData: "Data", stepReview: "Review", connectorHeading: "Choose a source connector", connectorLead: "Start with how data leaves the source system. Real credentials are not needed yet.", connectionHeading: "Describe the source and connection", connectionLead: "This creates the draft for a future live connector.", sourceName: "Source name", sourceNamePlaceholder: "SAP Production Orders", description: "Description", descriptionPlaceholder: "Where this data comes from and how it will be used", auth: "Authentication", schedule: "Polling interval", minutes: "minutes", credentialsNotice: "UX preview only — credentials, passwords and certificates are not stored here.", dataHeading: "Choose inbound data", dataLead: "One source can provide multiple domains that become standard SAM events.", selected: "Selected", eventPreview: "SAM event preview", reviewHeading: "Review source draft", reviewLead: "Saving does not connect to or read from the external system.", save: "Save source draft", saving: "Saving…", continue: "Continue", previous: "Back", required: "Enter a source name, choose a connector and select at least one data domain.", saveError: "Could not save source draft", notFound: "Source draft not found", previewOnly: "Design only · No inbound data",
  },
  ja: {
    title: "Data Sources", subtitle: "業務システム、設備、ファイル、現場からSAM Bridgeが受け取るデータを定義します。", create: "Data Sourceを追加", nameCol: "名前", connectorCol: "Connector", statusCol: "状態", actionsCol: "操作", emptyTitle: "Data Sourceはありません", drafts: "Source Draft", connectorTypes: "Connector種類", dataDomains: "Data Domain", configured: "設定済みSource", configuredHint: "すべてDraftで、外部システムへの接続はまだ有効ではありません。", empty: "Source Draftはありません。Data Sourceを追加して受信データを設計してください。", catalog: "Source Catalog", catalogHint: "Source SystemからSAM Bridgeへデータを渡す方法を選択します。", configure: "設定", edit: "編集", remove: "削除", draft: "Draft", site: "工場 / Site", owner: "担当者", mode: "受信方式", domains: "データ", updated: "更新", deleteTitle: "Source Draftを削除しますか？", deleteBody: "Draftのみ削除され、Source Systemには影響しません。", cancel: "キャンセル", confirmDelete: "Draftを削除", back: "Data Sources", newTitle: "Data Sourceを追加", editTitle: "Data Sourceを編集", stepConnector: "Connector", stepConnection: "Connection", stepData: "Data", stepReview: "Review", connectorHeading: "Source Connectorを選択", connectorLead: "Source Systemからデータを取得する方法を選びます。Credentialはまだ不要です。", connectionHeading: "SourceとConnectionを設定", connectionLead: "将来のLive Connector用Draftを作成します。", sourceName: "Source名", sourceNamePlaceholder: "SAP Production Orders", description: "説明", descriptionPlaceholder: "データの取得元と利用目的", auth: "Authentication", schedule: "Polling間隔", minutes: "分", credentialsNotice: "UX Previewのみ — Credential、Password、Certificateは保存されません。", dataHeading: "受信データを選択", dataLead: "1つのSourceから複数Domainを受信し、標準SAM Eventへ変換できます。", selected: "選択済み", eventPreview: "SAM Event Preview", reviewHeading: "Source Draftを確認", reviewLead: "保存しても外部システムへの接続やデータ取得は行いません。", save: "Source Draftを保存", saving: "保存中…", continue: "続ける", previous: "戻る", required: "Source名、Connector、1つ以上のData Domainを選択してください。", saveError: "Source Draftを保存できませんでした", notFound: "Source Draftが見つかりません", previewOnly: "Design only · No inbound data",
  },
} as const;
