export const COPY = {
  th: {
    title: "iXacs",
    intro: "จัดการเครื่องและการเชื่อมต่อ iXacs\nสำหรับรับข้อมูลจากไลน์ผลิตเข้าสู่ SAM Bridge",
    add: "เพิ่มเครื่อง",
    listTitle: "เครื่องที่เชื่อมต่อ",
    emptyTitle: "ยังไม่มีเครื่อง iXacs",
    emptyBody: "เพิ่มเครื่อง iXacs เพื่อเริ่มรับข้อมูลจากไลน์ผลิตเข้าสู่ SAM Bridge.",
    save: "บันทึกเครื่อง",
    saveChanges: "บันทึกการเปลี่ยนแปลง",
    cancel: "ยกเลิก",
    edit: "แก้ไข",
    remove: "ลบเครื่อง",
    use: "ใช้เครื่องนี้",
    test: "ทดสอบ",
    testConnection: "ทดสอบการเชื่อมต่อ",
    testing: "กำลังทดสอบ...",
    fetch: "ดูข้อมูล",
    more: "เพิ่มเติม",
    details: "ดูรายละเอียด",
    addTitle: "เพิ่มเครื่อง iXacs",
    editTitle: "แก้ไขเครื่อง",
    connection: "การเชื่อมต่อ",
    name: "ชื่อเครื่อง",
    nameHint: "เว้นว่างได้ — ระบบจะใช้ชื่อจากโฮสต์",
    baseUrl: "Base URL",
    openUrl: "เปิด URL",
    auth: "การเข้าสู่ระบบ",
    loginUrl: "Login URL",
    loginPath: "Login path",
    derivedLogin: "จะใช้",
    customerId: "IDบริษัทลูกค้า",
    loginId: "Login ID",
    password: "Password",
    passwordHint: "Password จะบันทึกไว้ฝั่งเซิร์ฟเวอร์เพื่อเข้าสู่ระบบใหม่เมื่อ session หมดอายุ และจะไม่ส่งกลับมาที่เบราว์เซอร์",
    showPassword: "แสดงรหัสผ่าน",
    hidePassword: "ซ่อนรหัสผ่าน",
    changePassword: "เปลี่ยนรหัสผ่าน",
    passwordUnset: "ไม่แสดงรหัสผ่านที่บันทึกไว้ กรอกใหม่เมื่อต้องการเปลี่ยนรหัสผ่าน",
    testLogin: "ทดสอบการเข้าสู่ระบบ",
    loginOkTitle: "เชื่อมต่อสำเร็จ",
    loginOkBody: "สามารถเข้าสู่ iXacs และสร้าง Session ได้แล้ว",
    loginFailTitle: "เชื่อมต่อไม่สำเร็จ",
    loginFailBody: "ตรวจสอบ Login URL, Login ID, Password และ IDบริษัทลูกค้า (หากบัญชีต้องใช้) แล้วลองอีกครั้ง",
    loginRequired: "กรอก Login ID และ Password ให้ครบ",
    selectCustomers: "เลือกลูกค้า",
    selectCustomersHint: "เลือกบริษัทที่จะผูกกับเครื่องนี้ — สลับดูข้อมูลได้ทีหลังในหน้าดูข้อมูล",
    selectCustomersEmpty: "เข้าสู่หน้าเลือกลูกค้าแล้ว แต่ดึงรายชื่อลูกค้าไม่สำเร็จ กรุณาลองใหม่หรือกรอกรหัสลูกค้าเอง",
    selectAtLeastOne: "เลือกลูกค้าอย่างน้อย 1 รายการ ก่อนบันทึก",
    selectThenSave: "เลือกลูกค้าด้านบน แล้วกดบันทึก",
    sessionCreated: "Session ถูกสร้างแล้ว",
    curl: "นำเข้าจาก cURL",
    curlToggle: "มี cURL อยู่แล้ว?",
    curlHint: "วางคำสั่ง cURL เพื่อดึง URL, Authentication และ Session อัตโนมัติ.",
    curlPlaceholder: "วางคำสั่ง cURL ที่นี่…",
    applyCurl: "วิเคราะห์ cURL",
    parsedTitle: "ตรวจพบข้อมูล",
    parsedAuth: "ตรวจพบ Basic Auth",
    parsedSession: "ตรวจพบ Session",
    parsedLines: (n: number) => `${n} ไลน์`,
    parsedNone: "ไม่พบ",
    advanced: "การตั้งค่าขั้นสูง",
    advancedHint: "Basic Auth, Session และข้อมูลดิบ",
    basicAuth: "Basic Auth",
    session: "Session",
    lines: "ข้อมูลไลน์ผลิต",
    linesHint: "หนึ่งบรรทัดต่อไลน์ หรือวาง productionLines= จาก cURL",
    linesCount: (n: number) => (n === 0 ? "ยังไม่มีไลน์" : `${n} ไลน์`),
    viewRaw: "ดูข้อมูลดิบ",
    hideRaw: "ซ่อนข้อมูลดิบ",
    show: "แสดง",
    hide: "ซ่อน",
    copy: "คัดลอก",
    copied: "คัดลอกแล้ว",
    statusOk: "เชื่อมต่อแล้ว",
    statusUnknown: "ยังไม่ได้ทดสอบ",
    statusError: "เชื่อมต่อไม่สำเร็จ",
    lastChecked: "ตรวจสอบล่าสุด",
    justNow: "เมื่อสักครู่",
    confirmTitle: "ลบเครื่องนี้?",
    confirmBody:
      "หลังจากลบ SAM Bridge จะไม่สามารถรับข้อมูลจากเครื่องนี้ได้อีกจนกว่าจะตั้งค่าการเชื่อมต่อใหม่.",
    fetched: (n: number, applied: number) =>
      `ดึงได้ ${n} ไลน์ อัปเดตแดชบอร์ด ${applied} ไลน์`,
    needLines: "ใส่ UUID ไลน์ในเครื่องนี้ก่อนดึงข้อมูล",
    lastError: "ล่าสุดล้มเหลว",
    saveError: "บันทึกไม่ได้ ลองอีกครั้ง",
    product: "งาน",
    status: "สถานะ",
    time: "เวลา",
    ct: "CT",
  },
  en: {
    title: "iXacs",
    intro: "Manage iXacs connections used to bring production data into SAM Bridge.",
    add: "Add machine",
    listTitle: "Connected machines",
    emptyTitle: "No iXacs machines yet",
    emptyBody: "Add an iXacs machine to start receiving production-line data into SAM Bridge.",
    save: "Save machine",
    saveChanges: "Save changes",
    cancel: "Cancel",
    edit: "Edit",
    remove: "Delete machine",
    use: "Use this machine",
    test: "Test",
    testConnection: "Test connection",
    testing: "Testing...",
    fetch: "View data",
    more: "More actions",
    details: "View details",
    addTitle: "Add iXacs machine",
    editTitle: "Edit machine",
    connection: "Connection",
    name: "Machine name",
    nameHint: "Optional — the host name is used when this is blank",
    baseUrl: "Base URL",
    openUrl: "Open URL",
    auth: "Sign in",
    loginUrl: "Login URL",
    loginPath: "Login path",
    derivedLogin: "Will use",
    customerId: "Customer ID",
    loginId: "Login ID",
    password: "Password",
    passwordHint: "The password is stored server-side for automatic sign-in when the session expires and is never returned to the browser.",
    showPassword: "Show password",
    hidePassword: "Hide password",
    changePassword: "Change password",
    passwordUnset: "The saved password is not displayed. Enter a value only to change it.",
    testLogin: "Test sign-in",
    loginOkTitle: "Connected",
    loginOkBody: "Signed in to iXacs and a session is ready.",
    loginFailTitle: "Could not connect",
    loginFailBody: "Check the Login URL, Login ID, Password, and Customer ID if your account requires one, then try again.",
    loginRequired: "Enter the Login ID and Password.",
    selectCustomers: "Select customers",
    selectCustomersHint: "Choose companies for this machine. You can switch between them later in View data.",
    selectCustomersEmpty: "Reached the customer selection page, but no customers could be listed. Try again or enter a Customer ID manually.",
    selectAtLeastOne: "Select at least one customer before saving.",
    selectThenSave: "Select customers above, then save",
    sessionCreated: "Session created",
    curl: "Import from cURL",
    curlToggle: "Have a cURL command already?",
    curlHint: "Paste a cURL command to fill URL, authentication, and session automatically.",
    curlPlaceholder: "Paste the cURL command here…",
    applyCurl: "Analyze cURL",
    parsedTitle: "Detected",
    parsedAuth: "Basic Auth detected",
    parsedSession: "Session detected",
    parsedLines: (n: number) => (n === 1 ? "1 line" : `${n} lines`),
    parsedNone: "Not found",
    advanced: "Advanced settings",
    advancedHint: "Basic Auth, Session, and raw data",
    basicAuth: "Basic Auth",
    session: "Session",
    lines: "Production lines",
    linesHint: "One UUID per line, or paste productionLines= from a cURL command.",
    linesCount: (n: number) => (n === 0 ? "No lines yet" : n === 1 ? "1 line" : `${n} lines`),
    viewRaw: "View raw data",
    hideRaw: "Hide raw data",
    show: "Show",
    hide: "Hide",
    copy: "Copy",
    copied: "Copied",
    statusOk: "Connected",
    statusUnknown: "Not tested yet",
    statusError: "Connection failed",
    lastChecked: "Last checked",
    justNow: "just now",
    confirmTitle: "Delete this machine?",
    confirmBody:
      "After deletion, SAM Bridge cannot receive data from this machine until it is connected again.",
    fetched: (n: number, applied: number) =>
      `Read ${n} lines, updated ${applied} on the dashboard`,
    needLines: "Add line UUIDs on this machine before pulling data.",
    lastError: "Last error",
    saveError: "Could not save. Try again.",
    product: "Product",
    status: "Status",
    time: "Time",
    ct: "CT",
  },
  ja: {
    title: "iXacs",
    intro: "生産データを SAM Bridge に取り込むための iXacs 接続を管理します。",
    add: "マシンを追加",
    listTitle: "接続中のマシン",
    emptyTitle: "iXacsマシンはまだありません",
    emptyBody: "iXacsマシンを追加して、生産ラインのデータを SAM Bridge へ取り込みます。",
    save: "マシンを保存",
    saveChanges: "変更を保存",
    cancel: "キャンセル",
    edit: "編集",
    remove: "マシンを削除",
    use: "このマシンを使う",
    test: "テスト",
    testConnection: "接続をテスト",
    testing: "テスト中...",
    fetch: "データを見る",
    more: "その他",
    details: "詳細を見る",
    addTitle: "iXacsマシンを追加",
    editTitle: "マシンを編集",
    connection: "接続",
    name: "マシン名",
    nameHint: "任意 — 空欄の場合はホスト名を使います",
    baseUrl: "Base URL",
    openUrl: "URLを開く",
    auth: "ログイン",
    loginUrl: "Login URL",
    loginPath: "Login path",
    derivedLogin: "使用するURL",
    customerId: "顧客ID",
    loginId: "ログインID",
    password: "パスワード",
    passwordHint: "セッション期限切れ時の自動再ログイン用にサーバー側へ保存され、ブラウザーへ返されません。",
    showPassword: "パスワードを表示",
    hidePassword: "パスワードを隠す",
    changePassword: "パスワードを変更",
    passwordUnset: "保存済みパスワードは表示されません。変更する場合のみ入力してください。",
    testLogin: "ログインをテスト",
    loginOkTitle: "接続できました",
    loginOkBody: "iXacs にログインし、Session を作成しました。",
    loginFailTitle: "接続できませんでした",
    loginFailBody: "Login URL、ログインID、パスワード、および必要な場合は顧客ID を確認してください。",
    loginRequired: "ログインID とパスワードを入力してください。",
    selectCustomers: "顧客を選択",
    selectCustomersHint: "このマシンに紐づける会社を選択します。データ画面で後から切り替えられます。",
    selectCustomersEmpty: "顧客選択ページには到達しましたが、顧客一覧を取得できませんでした。再試行するか顧客IDを直接入力してください。",
    selectAtLeastOne: "保存前に顧客を1つ以上選択してください。",
    selectThenSave: "上で顧客を選択してから保存してください",
    sessionCreated: "Session を作成しました",
    curl: "cURLから取り込み",
    curlToggle: "cURLコマンドがありますか？",
    curlHint: "cURL を貼ると URL、認証、Session を自動で取り込みます。",
    curlPlaceholder: "cURLコマンドを貼り付け…",
    applyCurl: "cURLを解析",
    parsedTitle: "検出された情報",
    parsedAuth: "Basic Auth を検出",
    parsedSession: "Session を検出",
    parsedLines: (n: number) => `${n} ライン`,
    parsedNone: "なし",
    advanced: "詳細設定",
    advancedHint: "Basic Auth、Session、生データ",
    basicAuth: "Basic Auth",
    session: "Session",
    lines: "生産ライン",
    linesHint: "1行に1UUID、または cURL の productionLines= を貼り付け",
    linesCount: (n: number) => (n === 0 ? "ラインなし" : `${n} ライン`),
    viewRaw: "生データを見る",
    hideRaw: "生データを隠す",
    show: "表示",
    hide: "隠す",
    copy: "コピー",
    copied: "コピー済み",
    statusOk: "接続済み",
    statusUnknown: "未テスト",
    statusError: "接続失敗",
    lastChecked: "最終確認",
    justNow: "たった今",
    confirmTitle: "このマシンを削除しますか？",
    confirmBody:
      "削除すると、再接続するまで SAM Bridge はこのマシンからデータを受け取れません。",
    fetched: (n: number, applied: number) =>
      `${n} ラインを取得、ダッシュボードは ${applied} ライン更新`,
    needLines: "データを取得する前に、このマシンへラインUUIDを追加してください。",
    lastError: "直前のエラー",
    saveError: "保存できませんでした。もう一度お試しください。",
    product: "製品",
    status: "状態",
    time: "時刻",
    ct: "CT",
  },
} as const;

export type Copy = (typeof COPY)[keyof typeof COPY];
