export const DX_COPY = {
  th: {
    crumbMachines: "iXacs",
    crumbData: "ข้อมูล",
    productionData: "ข้อมูลการผลิต",
    searchPlaceholder: "ค้นหางาน, ไลน์, UUID, สถานะ...",
    filters: "ตัวกรอง",
    columns: "คอลัมน์",
    refresh: "รีเฟรช",
    refreshHint: "รีเฟรชข้อมูล",
    refreshing: "กำลังดึง…",
    auto: "Auto",
    autoRefresh: "รีเฟรชอัตโนมัติ",
    autoOff: "ปิด",
    autoSec: "ช่วงเวลา Auto (วินาที)",
    autoUnit: "s",
    records: (n: number) => `${n.toLocaleString("th-TH")} รายการ`,
    updated: "อัปเดต",
    justNow: "เมื่อสักครู่",
    loading: "กำลังโหลดข้อมูลการผลิต…",
    emptyTitle: "ไม่มีข้อมูลการผลิต",
    emptyBody: "เครื่องนี้ยังไม่ส่งรายการกลับมา",
    errorTitle: "โหลดข้อมูลการผลิตไม่ได้",
    errorBody: "เชื่อมต่อเครื่องนี้ได้มาก่อน แต่ดึงข้อมูลครั้งนี้ไม่สำเร็จ",
    tryAgain: "ลองอีกครั้ง",
    needLines: "ใส่ UUID ไลน์ในเครื่องนี้ก่อนดึงข้อมูล",
    back: "กลับ",
    uuid: "UUID",
    product: "งาน",
    ct: "CT",
    time: "เวลา",
    status: "สถานะ",
    productUuid: "Product UUID",
    statusUuid: "Status UUID",
    productionGroup: "กลุ่มผลิต",
    productionGroupUuid: "Production Group UUID",
    productionLine: "ไลน์ผลิต",
    filterGroup: "กลุ่มผลิต",
    allGroups: "ทุกกลุ่ม",
    planNum: "Plan",
    actualNum: "Actual",
    currentCt: "Current CT",
    averageCt: "Avg. CT",
    baseCt: "Base CT",
    pcsPerHour: "PCS/H",
    volumeRate: "Volume Rate",
    operationalAvailability: "Operational Availability",
    operatingTime: "Operating Time",
    stopTime: "Stop Time",
    allProducts: "ทุกงาน",
    allStatuses: "ทุกสถานะ",
    ctAll: "CT ทั้งหมด",
    ctHas: "มีค่า CT",
    ctEmpty: "ไม่มี CT",
    clearFilters: "ล้างทั้งหมด",
    details: "รายละเอียดไลน์ผลิต",
    rawJson: "Raw JSON",
    copyJson: "คัดลอก JSON",
    copyValue: "คัดลอก",
    copied: "คัดลอกแล้ว",
    close: "ปิด",
    missing: "—",
    filterProduct: "งาน",
    filterStatus: "สถานะ",
    filterCt: "CT",
    switchMachine: "เลือกเครื่อง",
    switchCustomer: "เลือกบริษัทลูกค้า",
    selectedMachines: (n: number) => `${n.toLocaleString("th-TH")} เครื่อง`,
    selectedCustomers: (n: number) => `${n.toLocaleString("th-TH")} ลูกค้า`,
    allCustomers: "ลูกค้าทั้งหมด",
    selectAllCustomers: "เลือกทั้งหมด",
    clearCustomers: "ล้างการเลือก",
    company: "บริษัท",
    notFound: "ไม่พบเครื่องนี้",
  },
  en: {
    crumbMachines: "iXacs",
    crumbData: "Data",
    productionData: "Production data",
    searchPlaceholder: "Search product, line, UUID, status...",
    filters: "Filters",
    columns: "Columns",
    refresh: "Refresh",
    refreshHint: "Refresh data",
    refreshing: "Refreshing…",
    auto: "Auto",
    autoRefresh: "Auto refresh",
    autoOff: "Off",
    autoSec: "Auto interval (seconds)",
    autoUnit: "s",
    records: (n: number) => `${n.toLocaleString("en-US")} records`,
    updated: "Updated",
    justNow: "just now",
    loading: "Loading production data…",
    emptyTitle: "No production data",
    emptyBody: "No records were returned from this machine.",
    errorTitle: "Couldn’t load production data.",
    errorBody: "This machine connected before, but data could not be retrieved.",
    tryAgain: "Try again",
    needLines: "Add line UUIDs on this machine before pulling data.",
    back: "Back",
    uuid: "UUID",
    product: "Product",
    ct: "CT",
    time: "Time",
    status: "Status",
    productUuid: "Product UUID",
    statusUuid: "Status UUID",
    productionGroup: "Production group",
    productionGroupUuid: "Production Group UUID",
    productionLine: "Production line",
    filterGroup: "Production group",
    allGroups: "All groups",
    planNum: "Plan",
    actualNum: "Actual",
    currentCt: "Current CT",
    averageCt: "Avg. CT",
    baseCt: "Base CT",
    pcsPerHour: "PCS/H",
    volumeRate: "Volume Rate",
    operationalAvailability: "Operational Availability",
    operatingTime: "Operating Time",
    stopTime: "Stop Time",
    allProducts: "All products",
    allStatuses: "All statuses",
    ctAll: "Any CT",
    ctHas: "Has CT",
    ctEmpty: "No CT",
    clearFilters: "Clear all",
    details: "Production line details",
    rawJson: "Raw JSON",
    copyJson: "Copy JSON",
    copyValue: "Copy",
    copied: "Copied",
    close: "Close",
    missing: "—",
    filterProduct: "Product",
    filterStatus: "Status",
    filterCt: "CT",
    switchMachine: "Select machines",
    switchCustomer: "Select customers",
    selectedMachines: (n: number) => `${n.toLocaleString("en-US")} machines`,
    selectedCustomers: (n: number) => `${n.toLocaleString("en-US")} customers`,
    allCustomers: "All customers",
    selectAllCustomers: "Select all",
    clearCustomers: "Clear selection",
    company: "Company",
    notFound: "Machine not found",
  },
  ja: {
    crumbMachines: "iXacs",
    crumbData: "データ",
    productionData: "生産データ",
    searchPlaceholder: "製品、ライン、UUID、状態を検索...",
    filters: "フィルタ",
    columns: "列",
    refresh: "更新",
    refreshHint: "データを更新",
    refreshing: "取得中…",
    auto: "Auto",
    autoRefresh: "自動更新",
    autoOff: "オフ",
    autoSec: "Auto間隔（秒）",
    autoUnit: "s",
    records: (n: number) => `${n.toLocaleString("ja-JP")} 件`,
    updated: "更新",
    justNow: "たった今",
    loading: "生産データを読み込み中…",
    emptyTitle: "生産データがありません",
    emptyBody: "このマシンからレコードは返りませんでした。",
    errorTitle: "生産データを読み込めませんでした。",
    errorBody: "以前は接続できましたが、今回はデータを取得できませんでした。",
    tryAgain: "再試行",
    needLines: "データを取得する前に、このマシンへラインUUIDを追加してください。",
    back: "戻る",
    uuid: "UUID",
    product: "製品",
    ct: "CT",
    time: "時刻",
    status: "状態",
    productUuid: "Product UUID",
    statusUuid: "Status UUID",
    productionGroup: "生産グループ",
    productionGroupUuid: "Production Group UUID",
    productionLine: "生産ライン",
    filterGroup: "生産グループ",
    allGroups: "すべてのグループ",
    planNum: "Plan",
    actualNum: "Actual",
    currentCt: "Current CT",
    averageCt: "Avg. CT",
    baseCt: "Base CT",
    pcsPerHour: "PCS/H",
    volumeRate: "Volume Rate",
    operationalAvailability: "Operational Availability",
    operatingTime: "Operating Time",
    stopTime: "Stop Time",
    allProducts: "すべての製品",
    allStatuses: "すべての状態",
    ctAll: "CTすべて",
    ctHas: "CTあり",
    ctEmpty: "CTなし",
    clearFilters: "すべてクリア",
    details: "生産ラインの詳細",
    rawJson: "Raw JSON",
    copyJson: "JSONをコピー",
    copyValue: "コピー",
    copied: "コピー済み",
    close: "閉じる",
    missing: "—",
    filterProduct: "製品",
    filterStatus: "状態",
    filterCt: "CT",
    switchMachine: "マシンを選択",
    switchCustomer: "顧客を選択",
    selectedMachines: (n: number) => `${n.toLocaleString("ja-JP")} 台`,
    selectedCustomers: (n: number) => `${n.toLocaleString("ja-JP")} 顧客`,
    allCustomers: "すべての顧客",
    selectAllCustomers: "すべて選択",
    clearCustomers: "選択を解除",
    company: "会社",
    notFound: "マシンが見つかりません",
  },
} as const;

export type DxCopy = (typeof DX_COPY)[keyof typeof DX_COPY];
