import type { Locale } from "../../locale-context";
import type { IssuedKey, Named } from "./types";

export const COPY = {
  th: {
    title: "Push API",
    navSetup: "ตั้งค่า",
    navEvents: "ข้อมูล Push",
    eventsTitle: "ข้อมูล Push",
    company: "บริษัท",
    noCompany: "ยังไม่มีบริษัท",
    chooseCompany: "กรุณาเลือกบริษัทก่อนสร้าง API key",
    line: "ไลน์ผลิต",
    loadingCatalog: "กำลังโหลดไลน์...",
    noLines: "ไม่พบไลน์สำหรับบริษัทนี้",
    catalogError: "โหลดไลน์ไม่สำเร็จ",
    method: "POST",
    storageSupabase: "API Keys บันทึกใน Supabase — รับ push จาก iXacs และส่งสถานะกลับได้ตามเดิม",
    storageFile: "API Keys เก็บในไฟล์ local (ตั้งค่า SUPABASE_URL เพื่อใช้ Supabase)",
    keys: "API Keys",
    create: "Create key",
    search: "ค้นหาคีย์...",
    searchLines: "ค้นหาไลน์...",
    noLineMatch: "ไม่พบไลน์ที่ตรงกับคำค้น",
    status: "สถานะ",
    statusAll: "ทุกสถานะ",
    statusActive: "Active",
    statusDisabled: "Disabled",
    lineAll: "ทุกไลน์",
    copy: "คัดลอก",
    copied: "คัดลอกแล้ว",
    unused: "—",
    emptyTitle: "ยังไม่มี API key",
    emptyBody: "สร้างคีย์เพื่อเริ่มส่งเหตุการณ์จากไลน์ผลิตเข้า SAM Bridge",
    noMatch: "ไม่พบคีย์ที่ตรงกับตัวกรอง",
    expired: "Expired",
    createTitle: "สร้าง API key",
    name: "ชื่อคีย์",
    namePlaceholder: "เช่น DC#1 Production",
    environment: "Environment",
    envLive: "Live",
    envTest: "Test",
    expiration: "วันหมดอายุ",
    expNever: "ไม่หมดอายุ",
    exp30: "30 วัน",
    exp90: "90 วัน",
    exp365: "1 ปี",
    cancel: "ยกเลิก",
    createdTitle: "สร้างคีย์แล้ว",
    createdBody: "คัดลอกคีย์นี้ตอนนี้ ค่าเต็มจะไม่แสดงอีก",
    done: "เสร็จสิ้น",
    deleteTitle: "ลบ API key?",
    deleteBody: "แอปที่ใช้คีย์นี้จะส่งเหตุการณ์เข้ามาไม่ได้อีก",
    deleteAction: "ลบคีย์",
    copyKey: "คัดลอกคีย์",
    rotate: "หมุนคีย์",
    rotateTitle: "หมุน API key?",
    rotateBody: "คีย์เดิมจะใช้ไม่ได้ทันที คัดลอกคีย์ใหม่แล้วเก็บไว้ให้ปลอดภัย",
    rotateAction: "หมุนคีย์",
    enable: "เปิดใช้",
    disable: "ปิดใช้",
    createdAt: "สร้างเมื่อ",
    lastUsed: "ใช้ล่าสุด",
    maskedKey: "API key",
    createError: "สร้างคีย์ไม่ได้ ลองอีกครั้ง",
    deleteError: "ลบคีย์นี้ไม่ได้",
    rotateError: "หมุนคีย์นี้ไม่ได้",
    updateError: "อัปเดตคีย์ไม่ได้",
    loadError: "โหลดคีย์ไม่ได้ ลองอีกครั้ง",
    colName: "Name",
    colLine: "Production Line",
    colStatus: "Status",
    colUsed: "Last Used",
    justNow: "เมื่อสักครู่",
    minAgo: "นาทีที่แล้ว",
    hourAgo: "ชั่วโมงที่แล้ว",
    yesterday: "เมื่อวาน",
    daysAgo: "วันที่แล้ว",
    close: "ปิด",
  },
  en: {
    title: "Push API",
    navSetup: "Setup",
    navEvents: "Push data",
    eventsTitle: "Push data",
    company: "Company",
    noCompany: "No companies",
    chooseCompany: "Select a company before creating an API key.",
    line: "Production line",
    loadingCatalog: "Loading lines…",
    noLines: "No lines were found for this company.",
    catalogError: "Could not load production lines.",
    method: "POST",
    storageSupabase: "API keys are saved in Supabase — iXacs push in and status send-back work as before",
    storageFile: "API keys are stored in a local file (set SUPABASE_URL to use Supabase)",
    keys: "API Keys",
    create: "Create key",
    search: "Search keys…",
    searchLines: "Search lines…",
    noLineMatch: "No lines match this search.",
    status: "Status",
    statusAll: "All statuses",
    statusActive: "Active",
    statusDisabled: "Disabled",
    lineAll: "All lines",
    copy: "Copy",
    copied: "Copied",
    unused: "—",
    emptyTitle: "No API keys yet",
    emptyBody: "Create a credential to start sending production events to SAM Bridge.",
    noMatch: "No keys match the current filters.",
    expired: "Expired",
    createTitle: "Create API key",
    name: "Key name",
    namePlaceholder: "e.g. DC#1 Production",
    environment: "Environment",
    envLive: "Live",
    envTest: "Test",
    expiration: "Expiration",
    expNever: "Never",
    exp30: "30 days",
    exp90: "90 days",
    exp365: "1 year",
    cancel: "Cancel",
    createdTitle: "API key created",
    createdBody: "Copy this secret now. It will not be shown again.",
    done: "Done",
    deleteTitle: "Delete API key?",
    deleteBody: "Applications using this credential will no longer be able to push events.",
    deleteAction: "Delete key",
    copyKey: "Copy key",
    rotate: "Rotate key",
    rotateTitle: "Rotate API key?",
    rotateBody: "The current secret will stop working immediately. Copy the new key and store it securely.",
    rotateAction: "Rotate key",
    enable: "Enable",
    disable: "Disable",
    createdAt: "Created",
    lastUsed: "Last used",
    maskedKey: "API key",
    createError: "Couldn't create API key. Try again.",
    deleteError: "Couldn't delete this key.",
    rotateError: "Couldn't rotate this key.",
    updateError: "Couldn't update this key.",
    loadError: "Couldn't load API keys. Try again.",
    colName: "Name",
    colLine: "Production Line",
    colStatus: "Status",
    colUsed: "Last Used",
    justNow: "Just now",
    minAgo: "min ago",
    hourAgo: "hr ago",
    yesterday: "Yesterday",
    daysAgo: "days ago",
    close: "Close",
  },
  ja: {
    title: "Push API",
    navSetup: "設定",
    navEvents: "Pushデータ",
    eventsTitle: "Pushデータ",
    company: "Company",
    noCompany: "Companyがありません",
    chooseCompany: "APIキーを作成する前にCompanyを選択してください。",
    line: "Production Line",
    loadingCatalog: "ラインを読み込み中…",
    noLines: "このCompanyのラインが見つかりません。",
    catalogError: "ラインを読み込めませんでした。",
    method: "POST",
    storageSupabase: "APIキーは Supabase に保存 — iXacs からの受信とステータス送信は従来どおり",
    storageFile: "APIキーはローカルファイルに保存（Supabase を使う場合は SUPABASE_URL を設定）",
    keys: "API Keys",
    create: "Create key",
    search: "キーを検索…",
    searchLines: "ラインを検索…",
    noLineMatch: "一致するラインはありません。",
    status: "Status",
    statusAll: "すべてのStatus",
    statusActive: "Active",
    statusDisabled: "Disabled",
    lineAll: "すべてのライン",
    copy: "コピー",
    copied: "コピーしました",
    unused: "—",
    emptyTitle: "APIキーはまだありません",
    emptyBody: "認証情報を作成すると、生産イベントを SAM Bridge に送れます。",
    noMatch: "フィルタに一致するキーはありません。",
    expired: "Expired",
    createTitle: "APIキーを作成",
    name: "キー名",
    namePlaceholder: "例: DC#1 Production",
    environment: "Environment",
    envLive: "Live",
    envTest: "Test",
    expiration: "有効期限",
    expNever: "無期限",
    exp30: "30日",
    exp90: "90日",
    exp365: "1年",
    cancel: "キャンセル",
    createdTitle: "APIキーを作成しました",
    createdBody: "このシークレットを今すぐコピーしてください。再表示されません。",
    done: "完了",
    deleteTitle: "APIキーを削除しますか？",
    deleteBody: "この認証情報を使うアプリは、イベントを送れなくなります。",
    deleteAction: "キーを削除",
    copyKey: "キーをコピー",
    rotate: "キーをローテーション",
    rotateTitle: "APIキーをローテーションしますか？",
    rotateBody: "現在のシークレットはすぐに使えなくなります。新しいキーをコピーして安全に保管してください。",
    rotateAction: "ローテーション",
    enable: "有効化",
    disable: "無効化",
    createdAt: "作成日時",
    lastUsed: "最終使用",
    maskedKey: "API key",
    createError: "APIキーを作成できませんでした。再試行してください。",
    deleteError: "このキーを削除できませんでした。",
    rotateError: "このキーをローテーションできませんでした。",
    updateError: "このキーを更新できませんでした。",
    loadError: "APIキーを読み込めませんでした。再試行してください。",
    colName: "Name",
    colLine: "Production Line",
    colStatus: "Status",
    colUsed: "Last Used",
    justNow: "たった今",
    minAgo: "分前",
    hourAgo: "時間前",
    yesterday: "昨日",
    daysAgo: "日前",
    close: "閉じる",
  },
} as const;

export type Copy = (typeof COPY)[Locale];

export function localizedName(item: Named, locale: Locale) {
  if (locale === "en") return item.nameEn || item.nameTh || item.nameJa;
  if (locale === "ja") return item.nameJa || item.nameEn || item.nameTh;
  return item.nameTh || item.nameEn || item.nameJa;
}

export function lineLabel(item: IssuedKey, locale: Locale, unused: string) {
  if (!item.line) return unused;
  return localizedName(item.line, locale);
}

export function keyName(item: IssuedKey, locale: Locale) {
  return item.name?.trim() || lineLabel(item, locale, item.key.slice(0, 8));
}

export function maskKey(key: string) {
  if (key.length <= 12) return key;
  return `${key.slice(0, 8)}…${key.slice(-4)}`;
}

export function relativeUsed(iso: string | null, locale: Locale, copy: Copy) {
  if (!iso) return copy.unused;
  const delta = Date.now() - Date.parse(iso);
  if (!Number.isFinite(delta) || delta < 0) return copy.unused;
  const minutes = Math.floor(delta / 60_000);
  if (minutes < 1) return copy.justNow;
  if (minutes < 60) return locale === "en" ? `${minutes} ${copy.minAgo}` : `${minutes} ${copy.minAgo}`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return locale === "en" ? `${hours} ${copy.hourAgo}` : `${hours} ${copy.hourAgo}`;
  const days = Math.floor(hours / 24);
  if (days === 1) return copy.yesterday;
  return locale === "en" ? `${days} ${copy.daysAgo}` : `${days} ${copy.daysAgo}`;
}

export function formatDate(iso: string, locale: Locale) {
  return new Date(iso).toLocaleString(
    locale === "th" ? "th-TH" : locale === "ja" ? "ja-JP" : "en-GB",
    { dateStyle: "medium", timeStyle: "short" },
  );
}
