export const LOGIN_COPY = {
  th: {
    brand: "SAM Bridge",
    signIn: "เข้าสู่ระบบ",
    signInLead: "ใช้บัญชี iXacs ที่ผู้ดูแลเพิ่มไว้ในระบบ",
    adminLead: "เข้าสู่ระบบด้วยบัญชีผู้ดูแลจาก env หรือที่สร้างใน Admin Systems",
    adminFailed: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
    user: "ผู้ใช้",
    customerId: "IDบริษัทลูกค้า",
    loginId: "Login ID",
    password: "Password",
    submit: "เข้าสู่ระบบ",
    submitting: "กำลังเข้าสู่ระบบ...",
    failed: "IDบริษัทลูกค้า, Login ID หรือ Password ไม่ถูกต้อง",
    unreachable: "ไม่สามารถเชื่อมต่อกับเซิร์ฟเวอร์ได้",
    showPassword: "แสดงรหัสผ่าน",
    hidePassword: "ซ่อนรหัสผ่าน",
    footnote: "Production data, connected.",
  },
  en: {
    brand: "SAM Bridge",
    signIn: "Sign in",
    signInLead: "Use an iXacs account added by your administrator",
    adminLead: "Sign in with an admin account from env or Admin Systems",
    adminFailed: "Username or password is incorrect",
    user: "Username",
    customerId: "Customer ID",
    loginId: "Login ID",
    password: "Password",
    submit: "Login",
    submitting: "Signing in...",
    failed: "Customer ID, Login ID, or password is incorrect",
    unreachable: "Could not reach the server",
    showPassword: "Show password",
    hidePassword: "Hide password",
    footnote: "Production data, connected.",
  },
  ja: {
    brand: "SAM Bridge",
    signIn: "ログイン",
    signInLead: "管理者が追加した iXacs アカウントを使用します",
    adminLead: "env または Admin Systems で作成した管理者アカウントでログインします",
    adminFailed: "ユーザー名またはパスワードが正しくありません",
    user: "ユーザー名",
    customerId: "顧客ID",
    loginId: "ログインID",
    password: "パスワード",
    submit: "ログイン",
    submitting: "ログインしています...",
    failed: "顧客ID、ログインID、またはパスワードが正しくありません",
    unreachable: "サーバーに接続できませんでした",
    showPassword: "パスワードを表示",
    hidePassword: "パスワードを隠す",
    footnote: "Production data, connected.",
  },
} as const;

export type LoginCopy = {
  [Key in keyof (typeof LOGIN_COPY)["th"]]: string;
};
