import type { Locale } from "../../locale-context";

export const SYSTEMS_COPY = {
  th: {
    title: "Admin Systems",
    menuOverview: "ภาพรวม",
    overviewLead: "จัดการผู้ดูแลระบบ โมเดล AI การแจ้งเตือน และบันทึกของ SAM Bridge",
    descAdmins: "บัญชีและสิทธิ์ผู้ดูแลระบบ",
    descAi: "เชื่อมต่อ API และกำหนดโมเดลเริ่มต้น",
    descAlerts: "LINE Slack LINE WORKS และ Email",
    descHealth: "สถานะการทำงานของระบบ",
    descAudit: "ประวัติการเปลี่ยนแปลงของผู้ดูแล",
    descSessions: "ประวัติการเข้าสู่ระบบ",
    menuAdmins: "ผู้ดูแลระบบ",
    menuAi: "AI Models",
    menuAlerts: "การแจ้งเตือน",
    menuHealth: "สถานะระบบ",
    menuAudit: "บันทึกกิจกรรม",
    menuSessions: "บันทึกการเข้าใช้",
    addAdmin: "เพิ่มผู้ดูแลระบบ",
    addAdminLead: "บัญชีนี้ใช้เข้าสู่ระบบที่ /admin/login",
    editAdmin: "แก้ไขผู้ดูแลระบบ",
    editAdminLead: "เปลี่ยนชื่อผู้ใช้ หรือตั้งรหัสผ่านใหม่",
    showPassword: "แสดงรหัสผ่าน",
    hidePassword: "ซ่อนรหัสผ่าน",
    colUsername: "ชื่อผู้ใช้",
    colSource: "แหล่งที่มา",
    colCreated: "สร้างเมื่อ",
    sourceEnv: "จาก env",
    sourceApp: "บัญชีที่สร้าง",
    password: "รหัสผ่าน",
    newPassword: "รหัสผ่านใหม่",
    passwordHint: "เว้นว่างถ้าไม่ต้องการเปลี่ยน",
    usernamePlaceholder: "admin",
    emptyAdmins: "ยังไม่มีผู้ดูแลระบบ",
    envHint: "บัญชีจาก AUTH_USER เข้าได้ที่ /admin/login และแก้ที่ไฟล์ .env",
    cannotDeleteSelf: "ลบบัญชีของตัวเองไม่ได้",
    cannotDeleteEnv: "บัญชีจาก env ลบไม่ได้",
    usernameTaken: "ชื่อผู้ใช้นี้มีแล้ว",
    confirmPassword: "ยืนยันรหัสผ่าน",
    passwordShort: "รหัสผ่านต้องมีอย่างน้อย 8 ตัว และมีตัวพิมพ์ใหญ่ เล็ก ตัวเลข และสัญลักษณ์",
    passwordMismatch: "รหัสผ่านไม่ตรงกัน",
    passwordMatch: "รหัสผ่านตรงกัน",
    ruleLength: "อย่างน้อย 8 ตัวอักษร",
    ruleLong: "อย่างน้อย 12 ตัวอักษร",
    ruleUpper: "ตัวพิมพ์ใหญ่ (A–Z)",
    ruleLower: "ตัวพิมพ์เล็ก (a–z)",
    ruleNumber: "ตัวเลข (0–9)",
    ruleSymbol: "สัญลักษณ์พิเศษ (!@#…)",
    strengthWeak: "อ่อน",
    strengthFair: "พอใช้",
    strengthGood: "ดี",
    strengthStrong: "แข็งแรง",
    you: "คุณ",
    soon: "ยังไม่พร้อมใช้งาน",
    back: "กลับ",
    machines: "เครื่องที่มี LINE",
    users: "ผู้ใช้ LINE",
    online: "กำลังล็อกอิน",
    rules: "การแจ้งเตือน",
    search: "ค้นหาเครื่อง บริษัท หรือ user...",
    filterAll: "ทั้งหมด",
    filterUsers: "มีผู้ใช้",
    filterOnline: "กำลังล็อกอิน",
    colMachine: "เครื่อง iXacs",
    colCompany: "บริษัท / ลูกค้า",
    colUsers: "ผู้ใช้",
    colOnline: "ออนไลน์",
    colRules: "การแจ้งเตือน",
    colLast: "ล็อกอินล่าสุด",
    empty: "ยังไม่มีเครื่อง iXacs",
    emptyFilter: "ไม่พบเครื่องที่ตรงกับเงื่อนไขนี้",
    loadError: "โหลดข้อมูลไม่สำเร็จ",
    usersOf: "ผู้ใช้ LINE",
    navUsers: "ผู้ใช้",
    navAlerts: "Alert",
    searchUsers: "ค้นหาชื่อ LINE หรือ id...",
    noUsers: "ยังไม่มีผู้ใช้ล็อกอินผ่าน LINE",
    noUserMatch: "ไม่พบผู้ใช้ที่ตรงกับคำค้น",
    noRules: "ยังไม่มี Alert",
    noAlertMatch: "ไม่พบ Alert ที่ตรงกับคำค้น",
    ixacsId: "iXacs ID",
    lineId: "LINE user ID",
    navLine: "LINE",
    navSlack: "Slack",
    navLineWorks: "LINE WORKS",
    navEmail: "Email",
    comingSoon: "ยังไม่รองรับช่องทางนี้",
    setupNotify: "ไปตั้งค่า Notifications",
    emptyChannel: "ยังไม่มีการตั้งค่าในช่องทางนี้",
    loadingStatuses: "กำลังโหลดสถานะของไลน์...",
    colStatuses: "สถานะที่ตั้งค่า",
    statusActive: "ทำงานอยู่",
    statusError: "ผิดพลาด",
    colName: "โปรไฟล์ LINE",
    colGroup: "กลุ่ม",
    colLine: "ไลน์",
    colAlertStatus: "สถานะ",
    colDuration: "ระยะเวลา",
    colEnabled: "การทำงาน",
    colMenu: "รายการ",
    colDetail: "รายละเอียด",
    colActions: "จัดการ",
    edit: "แก้ไข",
    save: "บันทึก",
    cancel: "ยกเลิก",
    remove: "ลบ",
    editAlert: "แก้ไข Alert",
    saveError: "บันทึกไม่สำเร็จ",
    deleteError: "ลบไม่สำเร็จ",
    durationLabel: "หน่วงเวลาก่อนส่ง (นาที) · 0 = ส่งทันที",
    durationHint: "ใส่ 0 เพื่อแจ้งเตือนทันทีเมื่อสถานะเปลี่ยน หากใส่ 15 ระบบจะรอให้อยู่ในสถานะนั้นครบ 15 นาทีก่อนส่ง",
    loggedIn: "ออนไลน์",
    loggedOut: "ออฟไลน์",
    enabled: "เปิดใช้",
    paused: "หยุดชั่วคราว",
    duration: (n: number) => (n <= 0 ? "ทันที" : `${n} นาที`),
    lastNotified: "แจ้งล่าสุด",
    never: "—",
    close: "ปิด",
    refresh: "รีเฟรช",
    ofMachines: (n: number) => `${n} เครื่อง`,
    ofRules: (n: number) => `${n} รายการ`,
  },
  en: {
    title: "Admin Systems",
    menuOverview: "Overview",
    overviewLead: "Manage admins, AI models, alerts, and SAM Bridge records",
    descAdmins: "Admin accounts and permissions",
    descAi: "Connect APIs and set the default model",
    descAlerts: "LINE, Slack, LINE WORKS, and Email",
    descHealth: "System health and uptime",
    descAudit: "Admin activity history",
    descSessions: "Sign-in history",
    menuAdmins: "Admins",
    menuAi: "AI Models",
    menuAlerts: "Alerts",
    menuHealth: "Health",
    menuAudit: "Audit log",
    menuSessions: "Sessions",
    addAdmin: "Add admin",
    addAdminLead: "This account can sign in at /admin/login",
    editAdmin: "Edit admin",
    editAdminLead: "Change the username or set a new password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    colUsername: "Username",
    colSource: "Source",
    colCreated: "Created",
    sourceEnv: "From env",
    sourceApp: "Created account",
    password: "Password",
    newPassword: "New password",
    passwordHint: "Leave blank to keep the current password",
    usernamePlaceholder: "admin",
    emptyAdmins: "No admins yet",
    envHint: "The AUTH_USER account signs in at /admin/login and is changed in .env",
    cannotDeleteSelf: "You cannot delete your own account",
    cannotDeleteEnv: "The env account cannot be deleted",
    usernameTaken: "This username is already taken",
    confirmPassword: "Confirm password",
    passwordShort: "Password needs 8+ characters with upper, lower, number, and symbol",
    passwordMismatch: "Passwords do not match",
    passwordMatch: "Passwords match",
    ruleLength: "At least 8 characters",
    ruleLong: "At least 12 characters",
    ruleUpper: "Uppercase letter (A–Z)",
    ruleLower: "Lowercase letter (a–z)",
    ruleNumber: "Number (0–9)",
    ruleSymbol: "Special character (!@#…)",
    strengthWeak: "Weak",
    strengthFair: "Fair",
    strengthGood: "Good",
    strengthStrong: "Strong",
    you: "You",
    soon: "Coming soon",
    back: "Back",
    machines: "Machines with LINE",
    users: "LINE users",
    online: "Signed in",
    rules: "Notifications",
    search: "Search machine, company, or user…",
    filterAll: "All",
    filterUsers: "Has users",
    filterOnline: "Signed in",
    colMachine: "iXacs machine",
    colCompany: "Company / customer",
    colUsers: "Users",
    colOnline: "Online",
    colRules: "Notifications",
    colLast: "Last login",
    empty: "No iXacs machines yet",
    emptyFilter: "No machines match this filter",
    loadError: "Could not load usage data",
    usersOf: "LINE users",
    navUsers: "Users",
    navAlerts: "Alerts",
    searchUsers: "Search LINE name or id…",
    noUsers: "No one has signed in through LINE yet",
    noUserMatch: "No users match this search",
    noRules: "No alerts yet",
    noAlertMatch: "No alerts match this search",
    ixacsId: "iXacs ID",
    lineId: "LINE user ID",
    navLine: "LINE",
    navSlack: "Slack",
    navLineWorks: "LINE WORKS",
    navEmail: "Email",
    comingSoon: "This channel is not available yet",
    setupNotify: "Open Notifications setup",
    emptyChannel: "No settings for this channel yet",
    loadingStatuses: "Loading statuses for this line…",
    colStatuses: "Configured statuses",
    statusActive: "Active",
    statusError: "Error",
    colName: "LINE profile",
    colGroup: "Group",
    colLine: "Line",
    colAlertStatus: "Status",
    colDuration: "Duration",
    colEnabled: "State",
    colMenu: "Item",
    colDetail: "Details",
    colActions: "Actions",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    remove: "Delete",
    editAlert: "Edit alert",
    saveError: "Could not save",
    deleteError: "Could not delete",
    durationLabel: "Hold before send (minutes) · 0 = immediate",
    durationHint: "Use 0 to notify as soon as the status changes. Use 15 to wait until that status has lasted 15 minutes.",
    loggedIn: "Online",
    loggedOut: "Offline",
    enabled: "On",
    paused: "Paused",
    duration: (n: number) => (n <= 0 ? "Immediate" : `${n} min`),
    lastNotified: "Last sent",
    never: "—",
    close: "Close",
    refresh: "Refresh",
    ofMachines: (n: number) => `${n} machines`,
    ofRules: (n: number) => `${n} rules`,
  },
  ja: {
    title: "Admin Systems",
    menuOverview: "概要",
    overviewLead: "管理者、AIモデル、通知、SAM Bridge の記録を管理します",
    descAdmins: "管理者アカウントと権限",
    descAi: "APIを接続し、デフォルトモデルを設定",
    descAlerts: "LINE、Slack、LINE WORKS、Email",
    descHealth: "システムの稼働状態",
    descAudit: "管理者の操作履歴",
    descSessions: "ログイン履歴",
    menuAdmins: "管理者",
    menuAi: "AI Models",
    menuAlerts: "通知",
    menuHealth: "稼働状態",
    menuAudit: "操作ログ",
    menuSessions: "ログイン履歴",
    addAdmin: "管理者を追加",
    addAdminLead: "このアカウントは /admin/login からログインできます",
    editAdmin: "管理者を編集",
    editAdminLead: "ユーザー名の変更、または新しいパスワードの設定",
    showPassword: "パスワードを表示",
    hidePassword: "パスワードを隠す",
    colUsername: "ユーザー名",
    colSource: "ソース",
    colCreated: "作成",
    sourceEnv: "env",
    sourceApp: "作成したアカウント",
    password: "パスワード",
    newPassword: "新しいパスワード",
    passwordHint: "変更しない場合は空欄",
    usernamePlaceholder: "admin",
    emptyAdmins: "管理者はまだいません",
    envHint: "AUTH_USER のアカウントは /admin/login からログインし、.env で変更します",
    cannotDeleteSelf: "自分のアカウントは削除できません",
    cannotDeleteEnv: "env のアカウントは削除できません",
    usernameTaken: "このユーザー名は既に使われています",
    confirmPassword: "パスワードの確認",
    passwordShort: "パスワードは8文字以上で、大文字・小文字・数字・記号を含めてください",
    passwordMismatch: "パスワードが一致しません",
    passwordMatch: "パスワードが一致しています",
    ruleLength: "8文字以上",
    ruleLong: "12文字以上",
    ruleUpper: "英大文字 (A–Z)",
    ruleLower: "英小文字 (a–z)",
    ruleNumber: "数字 (0–9)",
    ruleSymbol: "記号 (!@#…)",
    strengthWeak: "弱い",
    strengthFair: "普通",
    strengthGood: "良い",
    strengthStrong: "強い",
    you: "自分",
    soon: "準備中",
    back: "戻る",
    machines: "LINE利用中の機器",
    users: "LINEユーザー",
    online: "ログイン中",
    rules: "通知",
    search: "機器・会社・ユーザーを検索…",
    filterAll: "すべて",
    filterUsers: "ユーザーあり",
    filterOnline: "ログイン中",
    colMachine: "iXacs 機器",
    colCompany: "会社 / 顧客",
    colUsers: "ユーザー",
    colOnline: "オンライン",
    colRules: "通知",
    colLast: "最終ログイン",
    empty: "iXacs 機器はまだありません",
    emptyFilter: "条件に一致する機器がありません",
    loadError: "利用状況を読み込めませんでした",
    usersOf: "LINEユーザー",
    navUsers: "ユーザー",
    navAlerts: "Alert",
    searchUsers: "LINE名またはIDを検索…",
    noUsers: "LINEからのログインはまだありません",
    noUserMatch: "一致するユーザーはありません",
    noRules: "Alertはまだありません",
    noAlertMatch: "一致するAlertはありません",
    ixacsId: "iXacs ID",
    lineId: "LINE user ID",
    navLine: "LINE",
    navSlack: "Slack",
    navLineWorks: "LINE WORKS",
    navEmail: "Email",
    comingSoon: "このチャネルはまだ未対応です",
    setupNotify: "Notifications設定を開く",
    emptyChannel: "このチャネルの設定はまだありません",
    loadingStatuses: "このラインのステータスを読み込み中…",
    colStatuses: "設定済みステータス",
    statusActive: "稼働中",
    statusError: "エラー",
    colName: "LINEプロフィール",
    colGroup: "グループ",
    colLine: "ライン",
    colAlertStatus: "ステータス",
    colDuration: "時間",
    colEnabled: "状態",
    colMenu: "項目",
    colDetail: "詳細",
    colActions: "操作",
    edit: "編集",
    save: "保存",
    cancel: "キャンセル",
    remove: "削除",
    editAlert: "Alertを編集",
    saveError: "保存できませんでした",
    deleteError: "削除できませんでした",
    durationLabel: "送信までの待機（分）· 0 = 即時",
    durationHint: "0 でステータス変更直後に通知します。15 にすると、その状態が15分続いた後に送信します。",
    loggedIn: "オンライン",
    loggedOut: "オフライン",
    enabled: "有効",
    paused: "一時停止",
    duration: (n: number) => (n <= 0 ? "即時" : `${n}分`),
    lastNotified: "最終通知",
    never: "—",
    close: "閉じる",
    refresh: "更新",
    ofMachines: (n: number) => `${n} 台`,
    ofRules: (n: number) => `${n} 件`,
  },
} as const;

export type SystemsCopy = (typeof SYSTEMS_COPY)[Locale];
