export const EXPORT_COPY = {
  th: {
    title: "Data Export",
    subtitle: "กำหนดว่าข้อมูลจาก iXacs จะถูกเตรียมเพื่อส่งไปที่ใด โดยทุกการตั้งค่าในหน้านี้ยังเป็น Draft",
    create: "สร้าง Export Draft",
    emptyTitle: "ยังไม่มี Export Draft",
    emptyBody: "สร้างการตั้งค่าแรกเพื่อเลือก Source, ข้อมูล และระบบปลายทาง",
    draft: "Draft",
    fields: "ฟิลด์",
    source: "แหล่งข้อมูล",
    destination: "ปลายทาง",
    updated: "แก้ไขล่าสุด",
    edit: "แก้ไข",
    remove: "ลบ",
    cancel: "ยกเลิก",
    confirmTitle: "ลบ Export นี้?",
    confirmBody: "หลังจากลบ การตั้งค่านี้จะหายไป และต้องสร้างใหม่หากต้องการส่งข้อมูลชุดนี้อีก",
    back: "Data Export",
    newTitle: "สร้าง Export Draft",
    editTitle: "แก้ไข Export Draft",
    disabled: "Configuration only · ยังไม่มีการส่งข้อมูลจริง",
    overview: "ข้อมูลทั่วไป",
    name: "ชื่อ Export",
    description: "คำอธิบาย",
    sourceScope: "Source และ Scope",
    connection: "iXacs Connection",
    allGroups: "ทุก Production Group",
    allLines: "ทุก Production Line",
    loadingScope: "กำลังโหลด Group และ Line…",
    retryScope: "โหลด Group และ Line อีกครั้ง",
    dataFields: "ข้อมูลที่จะส่งออก",
    dataFieldsHelp: "เลือกได้ทุกส่วนหรือเลือกเฉพาะฟิลด์ที่ระบบปลายทางต้องใช้",
    selectAll: "เลือกทั้งหมด",
    clearAll: "ล้างทั้งหมด",
    destinationSettings: "ระบบปลายทาง",
    destinationName: "ชื่อปลายทาง",
    credentialsLater: "Credential และการทดสอบ Connection จะเพิ่มเมื่อเปิดใช้งาน Connector จริง",
    delivery: "รูปแบบและ Trigger",
    format: "รูปแบบข้อมูล",
    trigger: "Trigger",
    manual: "Manual",
    schedule: "ตามเวลา",
    dataChange: "เมื่อข้อมูลเปลี่ยน",
    interval: "ทุกกี่นาที",
    changesOnly: "ส่งเฉพาะข้อมูลที่เปลี่ยน",
    includeNulls: "รวมฟิลด์ที่ไม่มีค่า",
    summary: "สรุป Draft",
    selectedFields: "ข้อมูลที่เลือก",
    selectedScope: "ขอบเขต",
    save: "บันทึก Draft",
    saving: "กำลังบันทึก…",
    saved: "บันทึก Draft แล้ว",
    saveError: "บันทึก Draft ไม่สำเร็จ",
    required: "กรอกชื่อ เลือก Connection และเลือกข้อมูลอย่างน้อยหนึ่งฟิลด์",
    notFound: "ไม่พบ Export Draft",
    noConnection: "ยังไม่มี iXacs Connection",
  },
  en: {
    title: "Data Export", subtitle: "Define how iXacs data will be prepared for destinations. Every configuration remains a draft.", create: "Create export draft", emptyTitle: "No export drafts", emptyBody: "Create the first configuration to choose a source, data and destination.", draft: "Draft", fields: "fields", source: "Source", destination: "Destination", updated: "Updated", edit: "Edit", remove: "Delete", cancel: "Cancel", confirmTitle: "Delete this export?", confirmBody: "After deleting, this draft will be gone. Create it again if you still need this destination.", back: "Data Export", newTitle: "Create export draft", editTitle: "Edit export draft", disabled: "Configuration only · No data will be sent", overview: "Overview", name: "Export name", description: "Description", sourceScope: "Source and scope", connection: "iXacs connection", allGroups: "All production groups", allLines: "All production lines", loadingScope: "Loading groups and lines…", retryScope: "Reload groups and lines", dataFields: "Data to export", dataFieldsHelp: "Select every section or only the fields required by the destination.", selectAll: "Select all", clearAll: "Clear all", destinationSettings: "Destination", destinationName: "Destination name", credentialsLater: "Credentials and connection testing will be added when the connector is enabled.", delivery: "Format and trigger", format: "Data format", trigger: "Trigger", manual: "Manual", schedule: "Schedule", dataChange: "When data changes", interval: "Every minutes", changesOnly: "Send changed records only", includeNulls: "Include fields without values", summary: "Draft summary", selectedFields: "Selected data", selectedScope: "Scope", save: "Save draft", saving: "Saving…", saved: "Draft saved", saveError: "Could not save draft", required: "Enter a name, choose a connection and select at least one field.", notFound: "Export draft not found", noConnection: "No iXacs connections yet",
  },
  ja: {
    title: "Data Export", subtitle: "iXacsデータの出力先と形式を設定します。現在はすべてドラフトです。", create: "Export Draftを作成", emptyTitle: "Export Draftはありません", emptyBody: "Source、データ、出力先を選択して最初の設定を作成します。", draft: "Draft", fields: "フィールド", source: "Source", destination: "出力先", updated: "更新", edit: "編集", remove: "削除", cancel: "キャンセル", confirmTitle: "このExportを削除しますか？", confirmBody: "削除するとこの設定はなくなります。同じ出力が必要なら、もう一度作成してください。", back: "Data Export", newTitle: "Export Draftを作成", editTitle: "Export Draftを編集", disabled: "設定のみ · データは送信されません", overview: "基本情報", name: "Export名", description: "説明", sourceScope: "Sourceと範囲", connection: "iXacs Connection", allGroups: "すべてのProduction Group", allLines: "すべてのProduction Line", loadingScope: "GroupとLineを読み込み中…", retryScope: "GroupとLineを再読み込み", dataFields: "出力データ", dataFieldsHelp: "すべて、または出力先に必要なフィールドだけを選択できます。", selectAll: "すべて選択", clearAll: "すべて解除", destinationSettings: "出力先", destinationName: "出力先名", credentialsLater: "Connector有効化時にCredentialと接続テストを追加します。", delivery: "形式とTrigger", format: "データ形式", trigger: "Trigger", manual: "Manual", schedule: "Schedule", dataChange: "データ変更時", interval: "間隔（分）", changesOnly: "変更データのみ", includeNulls: "値のないフィールドを含める", summary: "Draft概要", selectedFields: "選択データ", selectedScope: "範囲", save: "Draftを保存", saving: "保存中…", saved: "Draftを保存しました", saveError: "Draftを保存できませんでした", required: "名前、Connection、1つ以上のフィールドを選択してください。", notFound: "Export Draftが見つかりません", noConnection: "iXacs Connectionがありません",
  },
} as const;

export const WIZARD_COPY = {
  th: {
    createTitle: "สร้าง Export",
    stepSource: "Source",
    stepData: "Data",
    stepDestination: "Destination",
    stepMapping: "Mapping",
    stepReview: "Review",
    sourceHeading: "เลือกแหล่งข้อมูล",
    namePlaceholder: "SAP production confirmation",
    descPlaceholder: "ใช้อยู่กับอะไร — สั้น ๆ ก็พอ",
    scope: "Scope",
    scopeAll: "All production data",
    scopeAllHint: "ทุก Production Group และทุก Production Line",
    scopeCustom: "Select production groups and lines",
    scopeCustomHint: "เลือกเฉพาะกลุ่มและไลน์ที่ต้องส่ง",
    groups: "Production groups",
    lines: "Production lines",
    pickGroupFirst: "เลือก Production Group ก่อน เพื่อแสดงไลน์ที่เกี่ยวข้อง",
    dataHeading: "เลือกข้อมูลที่จะส่ง",
    dataDesc: "เลือกเฉพาะข้อมูลที่ระบบปลายทางต้องใช้",
    recommended: "Recommended",
    presetSummary: "Production summary",
    presetSummaryDesc: "Core production fields",
    presetPerformance: "Performance",
    presetPerformanceDesc: "Cycle time and operating metrics",
    presetFull: "Full record",
    presetFullDesc: "All available fields",
    presetCustom: "Custom",
    presetCustomDesc: "Choose fields manually",
    searchFields: "Search fields...",
    fieldsSelected: "fields selected",
    destHeading: "เลือกปลายทาง",
    destDesc: "กำหนดว่าข้อมูลชุดนี้จะถูกส่งไปที่ใด",
    categories: {
      api: "API & Integration",
      enterprise: "Enterprise",
      file: "File & Messaging",
      notify: "Notifications",
      analytics: "Analytics",
    },
    change: "Change",
    authentication: "Authentication",
    authNone: "None",
    authKey: "API key",
    authBearer: "Bearer token",
    method: "Method",
    formatCanonical: "Canonical JSON",
    formatCanonicalHint: "Recommended",
    formatFlat: "Flat JSON",
    formatCsv: "CSV",
    triggerWhen: "When should this export run?",
    comingLater: "Coming later",
    reviewHeading: "Review export",
    untitled: "Untitled export",
    allGroups: "All production groups",
    allLines: "All production lines",
    cancel: "Cancel",
    continue: "Continue",
    back: "Back",
    addConnection: "เพิ่มเครื่อง iXacs",
    savedLocal: "บันทึกเป็น Draft แล้ว",
  },
  en: {
    createTitle: "Create export",
    stepSource: "Source",
    stepData: "Data",
    stepDestination: "Destination",
    stepMapping: "Mapping",
    stepReview: "Review",
    sourceHeading: "Choose your data source",
    namePlaceholder: "SAP production confirmation",
    descPlaceholder: "What this export is for — keep it short",
    scope: "Scope",
    scopeAll: "All production data",
    scopeAllHint: "Every production group and line",
    scopeCustom: "Select production groups and lines",
    scopeCustomHint: "Send only the groups and lines you choose",
    groups: "Production groups",
    lines: "Production lines",
    pickGroupFirst: "Select a production group to see its lines",
    dataHeading: "Choose data",
    dataDesc: "Include only the fields the destination needs",
    recommended: "Recommended",
    presetSummary: "Production summary",
    presetSummaryDesc: "Core production fields",
    presetPerformance: "Performance",
    presetPerformanceDesc: "Cycle time and operating metrics",
    presetFull: "Full record",
    presetFullDesc: "All available fields",
    presetCustom: "Custom",
    presetCustomDesc: "Choose fields manually",
    searchFields: "Search fields...",
    fieldsSelected: "fields selected",
    destHeading: "Choose destination",
    destDesc: "Decide where this data should be sent",
    categories: {
      api: "API & Integration",
      enterprise: "Enterprise",
      file: "File & Messaging",
      notify: "Notifications",
      analytics: "Analytics",
    },
    change: "Change",
    authentication: "Authentication",
    authNone: "None",
    authKey: "API key",
    authBearer: "Bearer token",
    method: "Method",
    formatCanonical: "Canonical JSON",
    formatCanonicalHint: "Recommended",
    formatFlat: "Flat JSON",
    formatCsv: "CSV",
    triggerWhen: "When should this export run?",
    comingLater: "Coming later",
    reviewHeading: "Review export",
    untitled: "Untitled export",
    allGroups: "All production groups",
    allLines: "All production lines",
    cancel: "Cancel",
    continue: "Continue",
    back: "Back",
    addConnection: "Add an iXacs machine",
    savedLocal: "Draft saved",
  },
  ja: {
    createTitle: "Exportを作成",
    stepSource: "Source",
    stepData: "Data",
    stepDestination: "Destination",
    stepMapping: "Mapping",
    stepReview: "Review",
    sourceHeading: "データソースを選ぶ",
    namePlaceholder: "SAP production confirmation",
    descPlaceholder: "このExportの用途を短く",
    scope: "Scope",
    scopeAll: "All production data",
    scopeAllHint: "すべてのProduction GroupとLine",
    scopeCustom: "Select production groups and lines",
    scopeCustomHint: "送るGroupとLineだけを選ぶ",
    groups: "Production groups",
    lines: "Production lines",
    pickGroupFirst: "先にProduction Groupを選ぶとLineが表示されます",
    dataHeading: "送るデータを選ぶ",
    dataDesc: "出力先が必要なフィールドだけを含めます",
    recommended: "Recommended",
    presetSummary: "Production summary",
    presetSummaryDesc: "Core production fields",
    presetPerformance: "Performance",
    presetPerformanceDesc: "Cycle time and operating metrics",
    presetFull: "Full record",
    presetFullDesc: "All available fields",
    presetCustom: "Custom",
    presetCustomDesc: "Choose fields manually",
    searchFields: "Search fields...",
    fieldsSelected: "fields selected",
    destHeading: "出力先を選ぶ",
    destDesc: "このデータをどこへ送るかを決めます",
    categories: {
      api: "API & Integration",
      enterprise: "Enterprise",
      file: "File & Messaging",
      notify: "Notifications",
      analytics: "Analytics",
    },
    change: "Change",
    authentication: "Authentication",
    authNone: "None",
    authKey: "API key",
    authBearer: "Bearer token",
    method: "Method",
    formatCanonical: "Canonical JSON",
    formatCanonicalHint: "Recommended",
    formatFlat: "Flat JSON",
    formatCsv: "CSV",
    triggerWhen: "When should this export run?",
    comingLater: "Coming later",
    reviewHeading: "Review export",
    untitled: "Untitled export",
    allGroups: "All production groups",
    allLines: "All production lines",
    cancel: "Cancel",
    continue: "Continue",
    back: "Back",
    addConnection: "iXacsホストを追加",
    savedLocal: "Draftを保存しました",
  },
} as const;

export const SAP_COPY = {
  th: {
    heading: "SAP Connection",
    connectionName: "Connection name",
    namePlaceholder: "SAP Sandbox",
    environment: "Environment",
    sandbox: "Sandbox",
    api: "API",
    productionOrder: "Production Order",
    serviceUrl: "Service URL",
    serviceUrlPlaceholder: "วาง Service URL จาก SAP Business Accelerator Hub",
    serviceUrlHelp: "คัดลอกจาก API details / Code Snippet บน SAP Business Accelerator Hub",
    authentication: "Authentication",
    authType: "API Key",
    apiKey: "API Key",
    replace: "Replace",
    test: "Test Connection",
    testing: "Testing connection...",
    connected: "Connected",
    connectedTo: "Connected to SAP Sandbox",
    failed: "Connection failed",
    failedHint: "Check API Key and Service URL.",
    productionOrderApi: "Production Order API",
    testOperation: "Test operation",
    operation: "GET /ProductionOrder",
    lastTested: "Last tested",
    justNow: "Just now",
    testAgain: "Test again",
    edit: "Edit connection",
    disconnect: "Disconnect",
    required: "กรอก Service URL และ API Key",
    urlInvalid: "Service URL ต้องเป็น https จาก SAP Business Accelerator Hub",
    save: "บันทึกการเชื่อมต่อ SAP",
    saving: "กำลังบันทึก…",
    ready: "เชื่อมต่อแล้ว",
    missing: "ทดสอบการเชื่อมต่อ SAP ให้สำเร็จก่อน",
    actionHeading: "What should SAM do in SAP?",
    productionResult: "Production Result",
    productionResultHint: "ส่งจำนวน Actual จาก iXacs ไปเป็นผลการผลิต",
    customMapping: "Custom Mapping",
    customMappingHint: "กำหนด Mapping เอง",
    customLater: "ยังไม่เปิดในรอบนี้ — ใช้ Production Result",
    triggerManual: "Manual",
    triggerScheduled: "Scheduled",
    triggerConditional: "Conditional",
    mappingHeading: "Mapping",
    mappingDesc: "กำหนดว่าข้อมูลจาก iXacs จะถูกส่งเข้า SAP อย่างไร",
    selectOrder: "SAP Production Order",
    searchOrder: "Search order...",
    product: "Product",
    plant: "Plant",
    plannedQty: "Planned Qty",
    useOrder: "Use this order",
    changeOrder: "Change order",
    loadingOrders: "Loading production orders…",
    noOrders: "No production orders returned.",
    ordersError: "Could not load production orders from SAP.",
    dataMapping: "Data Mapping",
    ixacs: "iXacs",
    sap: "SAP",
    actualNum: "Actual Num",
    yieldQty: "Yield Quantity",
    productMap: "Product / validation",
    lineMap: "Context",
    timestamp: "Timestamp",
    confirmationTime: "Confirmation Time",
    confirmationUrl: "Confirmation Service URL",
    confirmationUrlHelp: "Paste from SAP Business Accelerator Hub → Production Order Confirmation → Code Snippet. Same API Key as this connection.",
    confirmationUrlPlaceholder: "Paste the Production Order Confirmation service URL",
    preview: "Preview",
    line: "Line",
    actual: "Actual",
    order: "Order",
    yield: "Yield",
    unit: "Unit",
    validate: "Validate Mapping",
    validated: "Mapping valid",
    validateNeedOrder: "Select a SAP Production Order.",
    validateNeedActual: "Actual Num is required for Yield Quantity.",
    validateNeedUrl: "Paste the Confirmation Service URL from SAP Business Accelerator Hub.",
    validateNeedAction: "Choose Production Result before continuing.",
    reviewAction: "Action",
    reviewActionValue: "Production Order Confirmation",
    reviewOrder: "Production Order",
    reviewMapping: "Mapping",
    mappingSummary: "Actual Num → Yield Quantity",
    previewPayload: "Preview Payload",
    sendTest: "Run Simulation",
    sendConfirmTitle: "Run SAP confirmation simulation?",
    sendCancel: "Cancel",
    sendOk: "Sent successfully",
    sendFail: "Send failed",
    needValidate: "Validate mapping before continuing.",
    selectedOrder: "Selected Production Order",
    realSapData: "Real SAP data",
    confirmation: "Production Confirmation",
    simulationMode: "Simulation Mode",
    simulationExplain: "SAP Business Accelerator Hub does not provide a POST sandbox for Production Order Confirmation. SAM will validate and simulate the request without sending production data to SAP.",
    simulationBadge: "SIMULATION",
    productRef: "Product reference",
    productionUnit: "Production Unit",
    payloadHeading: "SAP Production Confirmation Payload",
    payloadSub: "Simulation Preview",
    validatedReady: "Ready for simulation",
    validateNeedActualPositive: "Actual Num must be greater than 0.",
    validateNeedUnit: "Production Unit is required.",
    validateNeedPayload: "Could not build a valid confirmation payload.",
    noWrite: "No data will be written to SAP.",
    runSimulation: "Run Simulation",
    sendConfirmNote: "This will NOT modify SAP data.",
    simOk: "Simulation completed",
    simValidation: "Validation",
    simPassed: "Passed",
    simPayload: "Payload",
    simValid: "Valid",
    simWrite: "SAP write",
    simNotExecuted: "Not executed",
    simMode: "Mode",
    simModeValue: "Simulation",
    activity: "Export Activity",
    activitySimulated: "Simulated",
    mappedYield: "Mapped Yield",
    productionMapping: "Production Mapping",
    productionLine: "Production Line",
    sourceCompany: "Siam Asahi Manufacturing",
    reviewPoHeading: "SAP Production Order",
    reviewSandbox: "SAP Sandbox",
    flowRead: "Read Production Order",
    flowMap: "SAM Mapping",
    flowPayload: "Production Confirmation Payload",
    flowNotSent: "NOT SENT",
    flowReal: "REAL",
    activityTime: "Time",
    activityExport: "Export",
    activityDestination: "Destination",
    activityResult: "Result",
  },
  en: {
    heading: "SAP Connection",
    connectionName: "Connection name",
    namePlaceholder: "SAP Sandbox",
    environment: "Environment",
    sandbox: "Sandbox",
    api: "API",
    productionOrder: "Production Order",
    serviceUrl: "Service URL",
    serviceUrlPlaceholder: "Paste the Service URL from SAP Business Accelerator Hub",
    serviceUrlHelp: "Copy it from API details / Code Snippet on SAP Business Accelerator Hub.",
    authentication: "Authentication",
    authType: "API Key",
    apiKey: "API Key",
    replace: "Replace",
    test: "Test Connection",
    testing: "Testing connection...",
    connected: "Connected",
    connectedTo: "Connected to SAP Sandbox",
    failed: "Connection failed",
    failedHint: "Check API Key and Service URL.",
    productionOrderApi: "Production Order API",
    testOperation: "Test operation",
    operation: "GET /ProductionOrder",
    lastTested: "Last tested",
    justNow: "Just now",
    testAgain: "Test again",
    edit: "Edit connection",
    disconnect: "Disconnect",
    required: "Enter the Service URL and API Key.",
    urlInvalid: "Enter an https Service URL from SAP Business Accelerator Hub.",
    save: "Save SAP connection",
    saving: "Saving…",
    ready: "Connected",
    missing: "Test the SAP connection before continuing.",
    actionHeading: "What should SAM do in SAP?",
    productionResult: "Production Result",
    productionResultHint: "Send iXacs Actual quantity as a production result.",
    customMapping: "Custom Mapping",
    customMappingHint: "Define mapping yourself",
    customLater: "Not in this release — use Production Result.",
    triggerManual: "Manual",
    triggerScheduled: "Scheduled",
    triggerConditional: "Conditional",
    mappingHeading: "Mapping",
    mappingDesc: "Decide how iXacs data is sent into SAP.",
    selectOrder: "SAP Production Order",
    searchOrder: "Search order...",
    product: "Product",
    plant: "Plant",
    plannedQty: "Planned Qty",
    useOrder: "Use this order",
    changeOrder: "Change order",
    loadingOrders: "Loading production orders…",
    noOrders: "No production orders returned.",
    ordersError: "Could not load production orders from SAP.",
    dataMapping: "Data Mapping",
    ixacs: "iXacs",
    sap: "SAP",
    actualNum: "Actual Num",
    yieldQty: "Yield Quantity",
    productMap: "Product / validation",
    lineMap: "Context",
    timestamp: "Timestamp",
    confirmationTime: "Confirmation Time",
    confirmationUrl: "Confirmation Service URL",
    confirmationUrlHelp: "Paste from SAP Business Accelerator Hub → Production Order Confirmation → Code Snippet. Same API Key as this connection.",
    confirmationUrlPlaceholder: "Paste the Production Order Confirmation service URL",
    preview: "Preview",
    line: "Line",
    actual: "Actual",
    order: "Order",
    yield: "Yield",
    unit: "Unit",
    validate: "Validate Mapping",
    validated: "Mapping valid",
    validateNeedOrder: "Select a SAP Production Order.",
    validateNeedActual: "Actual Num is required for Yield Quantity.",
    validateNeedUrl: "Paste the Confirmation Service URL from SAP Business Accelerator Hub.",
    validateNeedAction: "Choose Production Result before continuing.",
    reviewAction: "Action",
    reviewActionValue: "Production Order Confirmation",
    reviewOrder: "Production Order",
    reviewMapping: "Mapping",
    mappingSummary: "Actual Num → Yield Quantity",
    previewPayload: "Preview Payload",
    sendTest: "Run Simulation",
    sendConfirmTitle: "Run SAP confirmation simulation?",
    sendCancel: "Cancel",
    sendOk: "Sent successfully",
    sendFail: "Send failed",
    needValidate: "Validate mapping before continuing.",
    selectedOrder: "Selected Production Order",
    realSapData: "Real SAP data",
    confirmation: "Production Confirmation",
    simulationMode: "Simulation Mode",
    simulationExplain: "SAP Business Accelerator Hub does not provide a POST sandbox for Production Order Confirmation. SAM will validate and simulate the request without sending production data to SAP.",
    simulationBadge: "SIMULATION",
    productRef: "Product reference",
    productionUnit: "Production Unit",
    payloadHeading: "SAP Production Confirmation Payload",
    payloadSub: "Simulation Preview",
    validatedReady: "Ready for simulation",
    validateNeedActualPositive: "Actual Num must be greater than 0.",
    validateNeedUnit: "Production Unit is required.",
    validateNeedPayload: "Could not build a valid confirmation payload.",
    noWrite: "No data will be written to SAP.",
    runSimulation: "Run Simulation",
    sendConfirmNote: "This will NOT modify SAP data.",
    simOk: "Simulation completed",
    simValidation: "Validation",
    simPassed: "Passed",
    simPayload: "Payload",
    simValid: "Valid",
    simWrite: "SAP write",
    simNotExecuted: "Not executed",
    simMode: "Mode",
    simModeValue: "Simulation",
    activity: "Export Activity",
    activitySimulated: "Simulated",
    mappedYield: "Mapped Yield",
    productionMapping: "Production Mapping",
    productionLine: "Production Line",
    sourceCompany: "Siam Asahi Manufacturing",
    reviewPoHeading: "SAP Production Order",
    reviewSandbox: "SAP Sandbox",
    flowRead: "Read Production Order",
    flowMap: "SAM Mapping",
    flowPayload: "Production Confirmation Payload",
    flowNotSent: "NOT SENT",
    flowReal: "REAL",
    activityTime: "Time",
    activityExport: "Export",
    activityDestination: "Destination",
    activityResult: "Result",
  },
  ja: {
    heading: "SAP Connection",
    connectionName: "Connection name",
    namePlaceholder: "SAP Sandbox",
    environment: "Environment",
    sandbox: "Sandbox",
    api: "API",
    productionOrder: "Production Order",
    serviceUrl: "Service URL",
    serviceUrlPlaceholder: "SAP Business Accelerator HubのService URLを貼り付け",
    serviceUrlHelp: "API details / Code Snippet からコピーします。",
    authentication: "Authentication",
    authType: "API Key",
    apiKey: "API Key",
    replace: "Replace",
    test: "Test Connection",
    testing: "Testing connection...",
    connected: "Connected",
    connectedTo: "Connected to SAP Sandbox",
    failed: "Connection failed",
    failedHint: "Check API Key and Service URL.",
    productionOrderApi: "Production Order API",
    testOperation: "Test operation",
    operation: "GET /ProductionOrder",
    lastTested: "Last tested",
    justNow: "Just now",
    testAgain: "Test again",
    edit: "Edit connection",
    disconnect: "Disconnect",
    required: "Service URLとAPI Keyを入力してください。",
    urlInvalid: "SAP Business Accelerator Hubのhttps Service URLを入力してください。",
    save: "SAP接続を保存",
    saving: "保存中…",
    ready: "接続済み",
    missing: "続ける前にSAP接続をテストしてください。",
    actionHeading: "What should SAM do in SAP?",
    productionResult: "Production Result",
    productionResultHint: "iXacsのActual数量を生産実績として送ります。",
    customMapping: "Custom Mapping",
    customMappingHint: "マッピングを自分で定義",
    customLater: "このリリースでは未対応です。Production Resultを使ってください。",
    triggerManual: "Manual",
    triggerScheduled: "Scheduled",
    triggerConditional: "Conditional",
    mappingHeading: "Mapping",
    mappingDesc: "iXacsデータをSAPへどう送るかを決めます。",
    selectOrder: "SAP Production Order",
    searchOrder: "Search order...",
    product: "Product",
    plant: "Plant",
    plannedQty: "Planned Qty",
    useOrder: "Use this order",
    changeOrder: "Change order",
    loadingOrders: "Loading production orders…",
    noOrders: "No production orders returned.",
    ordersError: "Could not load production orders from SAP.",
    dataMapping: "Data Mapping",
    ixacs: "iXacs",
    sap: "SAP",
    actualNum: "Actual Num",
    yieldQty: "Yield Quantity",
    productMap: "Product / validation",
    lineMap: "Context",
    timestamp: "Timestamp",
    confirmationTime: "Confirmation Time",
    confirmationUrl: "Confirmation Service URL",
    confirmationUrlHelp: "SAP Business Accelerator Hub → Production Order Confirmation → Code Snippet から貼り付けます。API Keyはこの接続と同じです。",
    confirmationUrlPlaceholder: "Production Order Confirmation の Service URL を貼り付け",
    preview: "Preview",
    line: "Line",
    actual: "Actual",
    order: "Order",
    yield: "Yield",
    unit: "Unit",
    validate: "Validate Mapping",
    validated: "Mapping valid",
    validateNeedOrder: "Select a SAP Production Order.",
    validateNeedActual: "Actual Num is required for Yield Quantity.",
    validateNeedUrl: "Paste the Confirmation Service URL from SAP Business Accelerator Hub.",
    validateNeedAction: "Choose Production Result before continuing.",
    reviewAction: "Action",
    reviewActionValue: "Production Order Confirmation",
    reviewOrder: "Production Order",
    reviewMapping: "Mapping",
    mappingSummary: "Actual Num → Yield Quantity",
    previewPayload: "Preview Payload",
    sendTest: "Run Simulation",
    sendConfirmTitle: "Run SAP confirmation simulation?",
    sendCancel: "Cancel",
    sendOk: "Sent successfully",
    sendFail: "Send failed",
    needValidate: "Validate mapping before continuing.",
    selectedOrder: "Selected Production Order",
    realSapData: "Real SAP data",
    confirmation: "Production Confirmation",
    simulationMode: "Simulation Mode",
    simulationExplain: "SAP Business Accelerator Hub does not provide a POST sandbox for Production Order Confirmation. SAM will validate and simulate the request without sending production data to SAP.",
    simulationBadge: "SIMULATION",
    productRef: "Product reference",
    productionUnit: "Production Unit",
    payloadHeading: "SAP Production Confirmation Payload",
    payloadSub: "Simulation Preview",
    validatedReady: "Ready for simulation",
    validateNeedActualPositive: "Actual Num must be greater than 0.",
    validateNeedUnit: "Production Unit is required.",
    validateNeedPayload: "Could not build a valid confirmation payload.",
    noWrite: "No data will be written to SAP.",
    runSimulation: "Run Simulation",
    sendConfirmNote: "This will NOT modify SAP data.",
    simOk: "Simulation completed",
    simValidation: "Validation",
    simPassed: "Passed",
    simPayload: "Payload",
    simValid: "Valid",
    simWrite: "SAP write",
    simNotExecuted: "Not executed",
    simMode: "Mode",
    simModeValue: "Simulation",
    activity: "Export Activity",
    activitySimulated: "Simulated",
    mappedYield: "Mapped Yield",
    productionMapping: "Production Mapping",
    productionLine: "Production Line",
    sourceCompany: "Siam Asahi Manufacturing",
    reviewPoHeading: "SAP Production Order",
    reviewSandbox: "SAP Sandbox",
    flowRead: "Read Production Order",
    flowMap: "SAM Mapping",
    flowPayload: "Production Confirmation Payload",
    flowNotSent: "NOT SENT",
    flowReal: "REAL",
    activityTime: "Time",
    activityExport: "Export",
    activityDestination: "Destination",
    activityResult: "Result",
  },
} as const;
