export const NOTIFY_COPY = {
  th: {
    title: "Notifications",
    subtitle: "กำหนดสถานะของไลน์ที่ต้องการแจ้งเตือน แล้วส่งไป LINE, Slack หรือ LINE WORKS",
    backToList: "กลับไปรายการ",
    create: "เพิ่มการแจ้งเตือน",
    lineWebhook: "LINE Webhook",
    editTitle: "แก้ไขการแจ้งเตือน",
    editHint: "ปรับช่องทาง เครื่อง ไลน์ หรือสถานะ แล้วบันทึก",
    saveChanges: "บันทึกการแก้ไข",
    webhookKeepHint: "เว้นว่างไว้หากไม่ต้องการเปลี่ยน Webhook",
    channelCol: "ช่องทาง",
    machine: "เครื่อง / ลูกค้า",
    scope: "ขอบเขต",
    linesCol: "ไลน์",
    statusesCol: "สถานะ",
    statusCol: "การทำงาน",
    actionsCol: "จัดการ",
    testOk: "ส่งข้อความทดสอบไป Slack สำเร็จ",
    deleteOk: "ลบกฎแล้ว",
    actionFailed: "ดำเนินการไม่สำเร็จ",
    testing: "กำลังทดสอบ…",
    saving: "กำลังบันทึก…",
    savedTitle: "ที่ตั้งค่าไว้แล้ว",
    savedHint: "การแจ้งเตือนที่บันทึกและทำงานอยู่",
    savedCount: (n: number) => `${n} รายการ`,
    setupTitle: "เพิ่มการแจ้งเตือนใหม่",
    setupHint: "เลือกช่องทาง เครื่อง ไลน์ และสถานะ แล้วบันทึก",
    stepChannel: "1 · ส่งไปที่",
    stepMachine: "2 · เลือกเครื่อง / ลูกค้า",
    stepScope: "3 · เลือกกลุ่มและไลน์",
    stepStatus: "4 · เลือกสถานะต่อไลน์",
    stepChannelHint: "เลือกช่องทางที่จะรับการแจ้งเตือน",
    stepMachineHint: "จากเครื่อง iXacs ใน Settings — กลุ่มจะแสดงลูกค้าข้างใน",
    stepScopeHint: "เลือกกลุ่มผลิต แล้วเลือกลายน์ที่ต้องการเฝ้าดู",
    stepStatusHint: "แสดงเฉพาะสถานะของไลน์ที่เปิดอยู่ — ไม่รวมไลน์อื่น",
    statusForLine: "เลือกสถานะของไลน์นี้",
    statusesPicked: (n: number) => (n === 0 ? "ยังไม่เลือกสถานะ" : `${n} สถานะ`),
    pickMachineFirst: "เลือกเครื่องหรือลูกค้าก่อน",
    pickLinesFirst: "เลือกไลน์ก่อน เพื่อเลือกสถานะของแต่ละไลน์",
    loadingMachines: "กำลังโหลดรายการเครื่อง…",
    loadingScope: "กำลังโหลดกลุ่มและไลน์จาก iXacs…",
    scopeError: "โหลดกลุ่ม/ไลน์ไม่สำเร็จ",
    noMachines: "ยังไม่มีเครื่อง iXacs ใน Settings",
    noGroups: "ไม่พบกลุ่มผลิต",
    noLines: "ไม่พบไลน์ในกลุ่มที่เลือก",
    noStatuses: "ไม่พบสถานะ",
    groups: "กลุ่มผลิต",
    lines: "ไลน์ผลิต",
    groupCustomers: (n: number) => `${n} ลูกค้า`,
    summary: "สรุป",
    summaryEmpty: "เลือกปลายทาง ไลน์ และสถานะเพื่อดูสรุป",
    summaryLine: (status: string, line: string, channel: string) =>
      `เมื่อไลน์ «${line}» เป็นสถานะ «${status}» → แจ้งเตือนไป ${channel}`,
    summaryMulti: (lineCount: number, statusCount: number, channel: string) =>
      `เมื่อ ${lineCount} ไลน์ เข้า ${statusCount} สถานะ → แจ้งเตือนไป ${channel}`,
    rules: "การแจ้งเตือนที่ตั้งไว้",
    draft: "ฉบับร่าง",
    save: "บันทึก",
    saveHint: "Slack พร้อมบันทึกและส่งจริง",
    monitorHint: "ส่งทันทีผ่าน Push API และตรวจซ้ำทุก 2 วินาทีขณะเปิดหน้านี้",
    comingSoon: "เร็วๆ นี้",
    edit: "แก้ไข",
    remove: "ลบ",
    testSlack: "ทดสอบ Slack",
    statusActive: "ทำงานอยู่",
    statusError: "ผิดพลาด",
    selectAll: "เลือกทั้งหมด",
    clear: "ล้าง",
    line: "LINE",
    slack: "Slack",
    lineWorks: "LINE WORKS",
    emptyRules: "ยังไม่มีการแจ้งเตือน",
    emptyRulesBody: "กด + เพื่อเพิ่มการแจ้งเตือนใหม่",
    ruleScope: (lines: number, statuses: number) => `${lines} ไลน์ · ${statuses} สถานะ`,
    webhookLabel: "Slack Incoming Webhook URL",
    webhookHint: "เก็บเป็นความลับฝั่ง Server และจะไม่แสดงอีกหลังบันทึก",
  },
  en: {
    title: "Notifications",
    subtitle: "Watch line statuses and notify LINE, Slack, or LINE WORKS",
    backToList: "Back to list",
    create: "Add alert",
    lineWebhook: "LINE Webhook",
    editTitle: "Edit alert",
    editHint: "Update channel, machine, lines, or statuses, then save",
    saveChanges: "Save changes",
    webhookKeepHint: "Leave blank to keep the current webhook",
    channelCol: "Channel",
    machine: "Machine / customer",
    scope: "Scope",
    linesCol: "Line",
    statusesCol: "Statuses",
    statusCol: "Health",
    actionsCol: "Actions",
    testOk: "Test message sent to Slack",
    deleteOk: "Alert removed",
    actionFailed: "Action failed",
    testing: "Testing…",
    saving: "Saving…",
    savedTitle: "Configured",
    savedHint: "Alerts that are saved and running",
    savedCount: (n: number) => `${n} rules`,
    setupTitle: "Add a new alert",
    setupHint: "Pick a channel, machine, lines, and statuses, then save",
    stepChannel: "1 · Send to",
    stepMachine: "2 · Machine / customer",
    stepScope: "3 · Groups & lines",
    stepStatus: "4 · Statuses per line",
    stepChannelHint: "Where the alert should arrive",
    stepMachineHint: "From iXacs machines in Settings — groups list their customers",
    stepScopeHint: "Pick production groups, then the lines to watch",
    stepStatusHint: "Only statuses for the open line — not other lines",
    statusForLine: "Statuses for this line",
    statusesPicked: (n: number) => (n === 0 ? "No statuses selected" : `${n} statuses`),
    pickMachineFirst: "Select a machine or customer first",
    pickLinesFirst: "Select lines first to choose statuses per line",
    loadingMachines: "Loading machines…",
    loadingScope: "Loading groups and lines from iXacs…",
    scopeError: "Could not load groups/lines",
    noMachines: "No iXacs machines in Settings yet",
    noGroups: "No production groups found",
    noLines: "No lines in the selected groups",
    noStatuses: "No statuses found",
    groups: "Production groups",
    lines: "Production lines",
    groupCustomers: (n: number) => `${n} customers`,
    summary: "Summary",
    summaryEmpty: "Pick a destination, lines, and statuses to preview the rule",
    summaryLine: (status: string, line: string, channel: string) =>
      `When line “${line}” is “${status}” → notify ${channel}`,
    summaryMulti: (lineCount: number, statusCount: number, channel: string) =>
      `When ${lineCount} lines hit ${statusCount} statuses → notify ${channel}`,
    rules: "Configured alerts",
    draft: "Draft",
    save: "Save",
    saveHint: "Slack saving and delivery are available",
    monitorHint: "Sends via Push API and rechecks every 2 seconds while this page is open",
    comingSoon: "Coming soon",
    edit: "Edit",
    remove: "Remove",
    testSlack: "Test Slack",
    statusActive: "Active",
    statusError: "Error",
    selectAll: "Select all",
    clear: "Clear",
    line: "LINE",
    slack: "Slack",
    lineWorks: "LINE WORKS",
    emptyRules: "No alerts yet",
    emptyRulesBody: "Press + to create a new alert",
    ruleScope: (lines: number, statuses: number) => `${lines} lines · ${statuses} statuses`,
    webhookLabel: "Slack Incoming Webhook URL",
    webhookHint: "Stored as a server secret and hidden after save",
  },
  ja: {
    title: "Notifications",
    subtitle: "ラインの状態を監視し、LINE / Slack / LINE WORKS へ通知します",
    backToList: "一覧に戻る",
    create: "通知を追加",
    lineWebhook: "LINE Webhook",
    editTitle: "通知を編集",
    editHint: "送信先・マシン・ライン・状態を更新して保存します",
    saveChanges: "変更を保存",
    webhookKeepHint: "変更しない場合は空のままにしてください",
    channelCol: "送信先",
    machine: "マシン / 顧客",
    scope: "範囲",
    linesCol: "ライン",
    statusesCol: "状態",
    statusCol: "稼働",
    actionsCol: "操作",
    testOk: "Slack へテストメッセージを送信しました",
    deleteOk: "通知を削除しました",
    actionFailed: "操作に失敗しました",
    testing: "テスト中…",
    saving: "保存中…",
    savedTitle: "設定済み",
    savedHint: "保存済みで動作中の通知",
    savedCount: (n: number) => `${n} 件`,
    setupTitle: "新しい通知を追加",
    setupHint: "送信先・マシン・ライン・状態を選んで保存します",
    stepChannel: "1 · 送信先",
    stepMachine: "2 · マシン / 顧客",
    stepScope: "3 · グループとライン",
    stepStatus: "4 · ラインごとの状態",
    stepChannelHint: "通知の送信先を選びます",
    stepMachineHint: "Settings の iXacs マシンから取得。グループは配下の顧客を表示します",
    stepScopeHint: "Production Group を選び、監視するラインを選択します",
    stepStatusHint: "開いているラインの状態だけを表示します",
    statusForLine: "このラインの状態",
    statusesPicked: (n: number) => (n === 0 ? "未選択" : `${n} 状態`),
    pickMachineFirst: "先にマシンまたは顧客を選んでください",
    pickLinesFirst: "先にラインを選ぶと、状態をラインごとに選べます",
    loadingMachines: "マシンを読み込み中…",
    loadingScope: "グループとラインを読み込み中…",
    scopeError: "グループ/ラインを読み込めませんでした",
    noMachines: "Settings に iXacs マシンがありません",
    noGroups: "Production Group がありません",
    noLines: "選択したグループにラインがありません",
    noStatuses: "状態が見つかりません",
    groups: "Production Group",
    lines: "Production Line",
    groupCustomers: (n: number) => `${n} 顧客`,
    summary: "概要",
    summaryEmpty: "送信先・ライン・状態を選ぶと概要が表示されます",
    summaryLine: (status: string, line: string, channel: string) =>
      `ライン「${line}」が「${status}」→ ${channel} へ通知`,
    summaryMulti: (lineCount: number, statusCount: number, channel: string) =>
      `${lineCount} ライン · ${statusCount} 状態 → ${channel} へ通知`,
    rules: "設定済みの通知",
    draft: "下書き",
    save: "保存",
    saveHint: "Slack の保存・送信が利用できます",
    monitorHint: "Push API で即時送信し、このページ表示中は 2 秒ごとに再確認します",
    comingSoon: "近日対応",
    edit: "編集",
    remove: "削除",
    testSlack: "Slack をテスト",
    statusActive: "稼働中",
    statusError: "エラー",
    selectAll: "すべて選択",
    clear: "解除",
    line: "LINE",
    slack: "Slack",
    lineWorks: "LINE WORKS",
    emptyRules: "通知はまだありません",
    emptyRulesBody: "+ から新しい通知を作成してください",
    ruleScope: (lines: number, statuses: number) => `${lines} ライン · ${statuses} 状態`,
    webhookLabel: "Slack Incoming Webhook URL",
    webhookHint: "サーバー側の秘密情報として保存され、保存後は再表示されません",
  },
} as const;
