-- Per-LINE-user AI conversation history and webhook idempotency/rate-limit records.
-- Message history is pruned by the application after 30 days.

create table if not exists public.line_ai_requests (
  event_id text primary key,
  line_user_id text not null references public.line_logins (line_user_id) on delete cascade,
  status text not null check (status in ('processing', 'completed', 'failed', 'rate_limited')),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists line_ai_requests_user_created_idx
  on public.line_ai_requests (line_user_id, created_at desc);

alter table public.line_ai_requests enable row level security;

create table if not exists public.line_ai_messages (
  id bigint generated by default as identity primary key,
  line_user_id text not null references public.line_logins (line_user_id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null check (char_length(content) <= 20000),
  created_at timestamptz not null default now()
);

create index if not exists line_ai_messages_user_created_idx
  on public.line_ai_messages (line_user_id, created_at desc);

alter table public.line_ai_messages enable row level security;
